all: e1 e2 e3 e4 e5 e6 e7 e8 e9 e9if e10 e11 e12 e13 e14

e1: Ejercicio1.c
	gcc Ejercicio1.c -o Ejercicio1.out

e2: Ejercicio2.c
	gcc Ejercicio2.c -o Ejercicio2.out

e3: Ejercicio3.c
	gcc Ejercicio3.c -o Ejercicio3.out

e4: Ejercicio4.c
	gcc Ejercicio4.c -o Ejercicio4.out

e5: Ejercicio5.c
	gcc Ejercicio5.c -o Ejercicio5.out

e6: Ejercicio6.c
	gcc Ejercicio6.c -o Ejercicio6.out

e7: Ejercicio7.c
	gcc Ejercicio7.c -o Ejercicio7.out

e8: Ejercicio8.c
	gcc Ejercicio8.c -o Ejercicio8.out

e9: Ejercicio9.c
	gcc Ejercicio9.c -o Ejercicio9.out

e9if: Ejercicio9if.c
	gcc Ejercicio9if.c -o Ejercicio9if.out

e10: Ejercicio10.c
	gcc Ejercicio10.c -o Ejercicio10.out

e11: Ejercicio11.c
	gcc Ejercicio11.c -o Ejercicio11.out

e12: Ejercicio12.c
	gcc Ejercicio12.c -o Ejercicio12.out

e13: Ejercicio13.c
	gcc Ejercicio13.c -o Ejercicio13.out

e14: Ejercicio14.c
	gcc Ejercicio14.c -o Ejercicio14.out

clean:
	rm Ejercici*.out
