
obj-m:= nothing.o ola.o memoria.o

main: calcu2.c
	gcc calcu2.c -o calcuplus.out
	gcc creararchivo.c -o creararchivo.out
	gcc gato.c -o gato.out -lpthread
	gcc hola.c -o hola.out -lpthread
	gcc imprimir.c -o imprimir.out -lpthread
	gcc procesos.c -o procesos.out
	gcc prog1.c -o prog1.out
	gcc prog2.c -o prog2.out
	gcc prog3.c -o prog3.out
	gcc prog4.c -o prog4.out
	gcc threads4.c -o threads4.out -lpthread
	gcc threads5.c -o threads5.out -lpthread
		
clean:

	rm calcuplus.out 
	rm creararchivo.out 	 
	rm gato.out
	rm hola.out 
	rm imprimir.out 
	rm procesos.out 
	rm prog1.out
	rm prog2.out 
	rm prog3.out
	rm prog4.out 
	rm threads4.out 
	rm threads5.out 

