calcuplus:
	gcc calcuplus2	 				-o calcuplus2.c
	gcc calcuplus3	 				-o calcuplus3.c
	gcc calcuplus	 				-o calcuplus.c

cuentacosas:
	gcc cuenta2numeros	 		-o cuenta2numeros.c
	gcc cuenta57	 				-o cuenta57.c
	gcc cuentaimpares	 		-o cuentaimpares.c
	gcc cuentanumero	 			-o cuentanumero.c
	gcc cuentaparimpar	 		-o cuentaparimpar.c
	gcc contador	 					-o contador.c

ficheros:
	gcc ficheros1	 				-o ficheros1.c

habitantes:
	gcc habitantes	 				-o habitantes.c
	gcc habitantesmedia	 		-o habitantesmedia.c
	gcc habitantespiso	 			-o habitantespiso.c
	gcc habitantespuerta	 		-o habitantespuerta.c

mallocs:
	gcc malloc1	 					-o malloc1.c
	gcc malloc2	 					-o malloc2.c
	gcc malloc3	 					-o malloc3.c

varios:
	gcc holaMundo	 				-o holaMundo.c
	gcc main	 						-o main.c
	gcc matriz	 						-o matriz.c
	gcc movetxt	 					-o movetxt.c
	gcc primerArray	 				-o primerArray.c
	gcc cosaarray	 				-o cosaarray.c
	gcc collatz	 					-o collatz.c
	gcc condicion	 				-o condicion.c
	gcc gestionEmpleados	 	-o gestionEmpleados.c

notas:
	gcc notas2	 					-o notas2.c
	gcc notas	 						-o notas.c
	gcc notasmenu	 				-o notasmenu.c

probaturas:
	gcc probCurses	 				-o probCurses.c
	gcc pruebaN	 					-o pruebaN.c
	gcc pruebatexto	 				-o pruebatexto.c
	gcc pulsa1	 					-o pulsa1.c
	gcc reinas	 						-o reinas.c
	
punteros:
	gcc punteros1	 				-o punteros1.c
	gcc punteros2	 				-o punteros2.c
	gcc punteros3	 				-o punteros3.c

calculitos:
	gcc rectangulo	 				-o rectangulo.c
	gcc resistencia	 				-o resistencia.c
	gcc rombo	 						-o rombo.c
	gcc salario	 					-o salario.c
	gcc saludos	 					-o saludos.c
	gcc segundos	 				-o segundos.c
	gcc parimpar	 					-o parimpar.c
	gcc potencia	 					-o potencia.c
	gcc maxcomundivisor	 	-o maxcomundivisor.c
	gcc mayormenor	 			-o mayormenor.c
	gcc media2	 					-o media2.c
	gcc media	 						-o media.c
	gcc primo	 						-o primo.c
	gcc multiplicar4	 				-o multiplicar4.c
	gcc preciodescuento	 		-o preciodescuento.c
	gcc funcionmayor	 			-o funcionmayor.c

calculitos2:
	gcc dias	 						-o dias.c
	gcc divisores	 					-o divisores.c
	gcc divisorescomunes	 	-o divisorescomunes.c
	gcc dolares	 					-o dolares.c
	gcc ecuacion	 					-o ecuacion.c
	gcc euros	 						-o euros.c
	gcc factorial	 					-o factorial.c
	gcc 7numeros	 				-o 7numeros.c
	gcc altobajo	 					-o altobajo.c
	gcc arbol	 						-o arbol.c
	gcc areas	 						-o areas.c
	gcc asteriscos	 				-o asteriscos.c
	gcc circulos	 					-o circulos.c
	
structs:
	gcc struct1	 					-o struct1.c
	
hilos:
	gcc threads1	 					-o threads1.c -lpthread
	gcc threadsPrueba	 			-o threadsPrueba.c -lpthread

clean: 
	rm *.out
