calcuplus:
	gcc -o  calcuplus2	 				calcuplus2.c
	gcc -o  calcuplus3	 				calcuplus3.c
	gcc -o  calcuplus	 				calcuplus.c

cuentacosas:
	gcc -o  cuenta2numeros	 		cuenta2numeros.c
	gcc -o  cuenta57	 				cuenta57.c
	gcc -o  cuentaimpares	 		cuentaimpares.c
	gcc -o  cuentanumero	 		cuentanumero.c
	gcc -o  cuentaparimpar	 		cuentaparimpar.c
	gcc -o  contador	 				contador.c

ficheros:
	gcc -o  ficheros1	 				ficheros1.c

habitantes:
	gcc -o  habitantes	 				habitantes.c
	gcc -o  habitantesmedia	 		habitantesmedia.c
	gcc -o  habitantespiso	 		habitantespiso.c
	gcc -o  habitantespuerta	 		habitantespuerta.c

mallocs:
	gcc -o  malloc1	 					malloc1.c
	gcc -o  malloc2	 					malloc2.c
	gcc -o  malloc3	 					malloc3.c

varios:
	gcc -o  holaMundo	 				holaMundo.c
	gcc -o  main	 						main.c
	gcc -o  matriz	 					matriz.c
	gcc -o  movetxt	 					movetxt.c
	gcc -o  primerArray	 			primerArray.c
	gcc -o  cosaarray	 				cosaarray.c
	gcc -o  collatz	 					collatz.c
	gcc -o  condicion	 				condicion.c
	gcc -o  gestionEmpleados	 	gestionEmpleados.c

notas:
	gcc -o  notas2	 					notas2.c
	gcc -o  notas	 						notas.c
	gcc -o  notasmenu	 				notasmenu.c

probaturas:
	gcc -o  probCurses	 			probCurses.c
	gcc -o  pruebaN	 					pruebaN.c
	gcc -o  pruebatexto	 			pruebatexto.c
	gcc -o  pulsa1	 					pulsa1.c
	gcc -o  reinas	 					reinas.c
	
punteros:
	gcc -o  punteros1	 				punteros1.c
	gcc -o  punteros2	 				punteros2.c
	gcc -o  punteros3	 				punteros3.c

calculitos:
	gcc -o  rectangulo	 				rectangulo.c
	gcc -o  resistencia	 				resistencia.c
	gcc -o  rombo	 					rombo.c
	gcc -o  salario	 					salario.c
	gcc -o  saludos	 					saludos.c
	gcc -o  segundos	 				segundos.c
	gcc -o  parimpar	 				parimpar.c
	gcc -o  potencia	 					potencia.c
	gcc -o  maxcomundivisor	 	maxcomundivisor.c
	gcc -o  mayormenor	 			mayormenor.c
	gcc -o  media2	 					media2.c
	gcc -o  media	 					media.c
	gcc -o  primo	 						primo.c
	gcc -o  multiplicar4	 			multiplicar4.c
	gcc -o  preciodescuento	 		preciodescuento.c
	gcc -o  funcionmayor	 			funcionmayor.c

calculitos2:
	gcc -o  dias	 						dias.c
	gcc -o  divisores	 				divisores.c
	gcc -o  divisorescomunes	 	divisorescomunes.c
	gcc -o  dolares	 					dolares.c
	gcc -o  ecuacion	 				ecuacion.c
	gcc -o  euros	 						euros.c
	gcc -o  factorial	 					factorial.c
	gcc -o  7numeros	 				7numeros.c
	gcc -o  altobajo	 					altobajo.c
	gcc -o  arbol	 						arbol.c
	gcc -o  areas	 						areas.c
	gcc -o  asteriscos	 				asteriscos.c
	gcc -o  circulos	 					circulos.c
	
structs:
	gcc -o  struct1	 					struct1.c
	
hilos:
	gcc -o  threads1	 				threads1.c -lpthread
	gcc -o  threadsPrueba	 		threadsPrueba.c -lpthread

clean: 
	rm *.out
