build: build_procesos build_threads
build_procesos:
	make build -C ej-procesos
build_threads:
	make build -C ej-threads
clean: clean_procesos clean_threads
clean_procesos:
	make clean -C ej-procesos -i
clean_threads:
	make clean -C ej-threads -i
