all: 1_trabajadores.cpp lib/dni.h lib/persona.h lib/asalariado.h lib/obrero.h lib/medico.h 4_inmobiliaria.cpp lib/local.h lib/hosteleria.h lib/ropa.h lib/ferreteria.h lib/comida.h lib/drogueria.h lib/bar.h lib/restaurante.h lib/comidallevar.h lib/camiseria.h lib/merceria.h lib/sombrereria.h lib/panaderia.h lib/carniceria.h lib/fruteria.h
	g++ 1_trabajadores.cpp -o trabajadores.o
	g++ 4_inmobiliaria.cpp -o inmobiliaria.o
clean:
	rm -f *.o
