/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ivamova.guiprogramadod;

import java.awt.Component;
import java.lang.reflect.Array;
import java.util.Arrays;
import javax.swing.JCheckBox;

/**
 *
 * @author Usuario
 */
public class Ventana extends javax.swing.JFrame {
    
    private String ingredientes[]={"chourizo", "jamón", "queso", "morcilla", 
        "champiñon", "lubrigante", "grelos", "piña", "maracuya", "chistorra", 
        "polbo","lechuga","bacon","aceitunas","atun","pollo"};
    private Double precioIngre[]={0.1,0.5,0.1,0.2,0.1,2.0,0.25,0.4,0.6,0.2,1.0,0.2,0.2,0.1,0.25,0.2};
    private String masas[]={"hiperextramegafina", "hipermegafina", "extrahiperfina", 
        "megaextrafina", "extrafina", "megafina", "hiperfina", "fina"};
    private double precioMasa[]={10,10.5,11,11.5,12,12.5,13,13.5};
    private String descuento[]={"0","5","10","20","50"};
    private Pedido pedido=new Pedido();

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        for(int contador=0;contador<masas.length;contador++){
            cbxMasa.addItem(masas[contador]);
        }
        Component[] componentes=pnPrincipal.getComponents();
        int contIngre=0;
        for(int contador=0;contador<componentes.length;contador++){
            if(componentes[contador] instanceof JCheckBox){
                ((JCheckBox)componentes[contador]).setText(ingredientes[contIngre]);
                contIngre++;
            }            
        }
        for(int contador=0;contador<descuento.length;contador++){
            cbxDescuento.addItem(descuento[contador]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgEntrega = new javax.swing.ButtonGroup();
        pnPrincipal = new javax.swing.JPanel();
        lblDescuento = new javax.swing.JLabel();
        cbxDescuento = new javax.swing.JComboBox<>();
        cbxMasa = new javax.swing.JComboBox<>();
        lblMasa = new javax.swing.JLabel();
        lblEntrega = new javax.swing.JLabel();
        rbLocal = new javax.swing.JRadioButton();
        rbDomicilio = new javax.swing.JRadioButton();
        txfCliente = new javax.swing.JTextField();
        lblCliente = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txfDireccion = new javax.swing.JTextField();
        btPedido = new javax.swing.JButton();
        btnMostrar2 = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        btIngredinetes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDescuento.setText("Descuento:");

        lblMasa.setText("Masa:");

        lblEntrega.setText("Forma de entrega");

        btgEntrega.add(rbLocal);
        rbLocal.setSelected(true);
        rbLocal.setText("En local");
        rbLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLocalActionPerformed(evt);
            }
        });

        btgEntrega.add(rbDomicilio);
        rbDomicilio.setText("En domicilio");
        rbDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDomicilioActionPerformed(evt);
            }
        });

        txfCliente.setEnabled(false);

        lblCliente.setText("Cliente:");
        lblCliente.setEnabled(false);

        lblDireccion.setText("Direccion:");
        lblDireccion.setEnabled(false);

        txfDireccion.setEnabled(false);

        btPedido.setText("HACER PEDIDO");
        btPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPedidoActionPerformed(evt);
            }
        });

        btnMostrar2.setText("MOSTRAR");
        btnMostrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrar2ActionPerformed(evt);
            }
        });

        btReset.setText("RESET");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        btIngredinetes.setText("INGREDIENTES");
        btIngredinetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngredinetesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPrincipalLayout.createSequentialGroup()
                        .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnPrincipalLayout.createSequentialGroup()
                                .addComponent(lblMasa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxMasa, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnPrincipalLayout.createSequentialGroup()
                                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDireccion)
                                    .addComponent(lblCliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfDireccion)
                                    .addComponent(txfCliente, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(pnPrincipalLayout.createSequentialGroup()
                                .addComponent(lblDescuento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnPrincipalLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rbLocal)
                                    .addComponent(lblEntrega))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbDomicilio)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(pnPrincipalLayout.createSequentialGroup()
                        .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnPrincipalLayout.createSequentialGroup()
                                .addComponent(btPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMostrar2))
                            .addComponent(btIngredinetes))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMasa)
                    .addComponent(cbxMasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(btIngredinetes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescuento)
                    .addComponent(cbxDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblEntrega)
                .addGap(18, 18, 18)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbLocal)
                    .addComponent(rbDomicilio))
                .addGap(18, 18, 18)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCliente))
                .addGap(18, 18, 18)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPedido)
                    .addComponent(btnMostrar2)
                    .addComponent(btReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLocalActionPerformed
        txfCliente.setEnabled(false);
        lblCliente.setEnabled(false);
        txfDireccion.setEnabled(false);
        lblDireccion.setEnabled(false);
    }//GEN-LAST:event_rbLocalActionPerformed

    private void rbDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDomicilioActionPerformed
        txfCliente.setEnabled(true);
        lblCliente.setEnabled(true);
        txfDireccion.setEnabled(true);
        lblDireccion.setEnabled(true);
    }//GEN-LAST:event_rbDomicilioActionPerformed

    private void btPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPedidoActionPerformed
        String masa=cbxMasa.getSelectedItem().toString();
        String descuento=cbxDescuento.getSelectedItem().toString();
        String entrega;
        String cliente="";
        String direccion="";
        if(rbDomicilio.isSelected()){
            entrega="Domicilio";
            cliente=txfCliente.getText();
            direccion=txfDireccion.getText();
        }else
        {
            entrega="Local";
        } 
        
        Double[] precios=pedido.getPrecios();
        precios[0]=precioMasa[cbxMasa.getSelectedIndex()];
        pedido.setPrecios(precios);
        pedido.setMasa(masa);
        pedido.setDescuento(descuento);
        pedido.setEntrega(entrega);
        if(entrega.equalsIgnoreCase("Domicilio")){
            pedido.setCliente(cliente);
            pedido.setDireccion(direccion);
        }
    }//GEN-LAST:event_btPedidoActionPerformed

    private void btnMostrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrar2ActionPerformed
        Mostrar mostrar=new Mostrar(pedido);
        mostrar.setVisible(true);
    }//GEN-LAST:event_btnMostrar2ActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        cbxMasa.setSelectedIndex(0);
        cbxDescuento.setSelectedIndex(0);
        rbLocal.setSelected(true);
        txfCliente.setEnabled(false);
        lblCliente.setEnabled(false);
        txfDireccion.setEnabled(false);
        lblDireccion.setEnabled(false);
        txfCliente.setText("");
        txfDireccion.setText("");
        pedido=new Pedido();
    }//GEN-LAST:event_btResetActionPerformed

    private void btIngredinetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngredinetesActionPerformed
        Ingredientes ingredientes=new Ingredientes(pedido,this.ingredientes,this.precioIngre);
        ingredientes.setVisible(true);
        pedido=ingredientes.getPedido();
        this.ingredientes=ingredientes.getIngredientes();
        this.precioIngre=ingredientes.getPrecioIngre();
    }//GEN-LAST:event_btIngredinetesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIngredinetes;
    private javax.swing.JButton btPedido;
    private javax.swing.JButton btReset;
    private javax.swing.ButtonGroup btgEntrega;
    private javax.swing.JButton btnMostrar2;
    private javax.swing.JComboBox<String> cbxDescuento;
    private javax.swing.JComboBox<String> cbxMasa;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEntrega;
    private javax.swing.JLabel lblMasa;
    private javax.swing.JPanel pnPrincipal;
    private javax.swing.JRadioButton rbDomicilio;
    private javax.swing.JRadioButton rbLocal;
    private javax.swing.JTextField txfCliente;
    private javax.swing.JTextField txfDireccion;
    // End of variables declaration//GEN-END:variables
}
