/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ivamova.guiprogramadod;

import java.awt.Component;
import java.lang.reflect.Array;
import java.util.Arrays;
import javax.swing.JCheckBox;

/**
 *
 * @author Usuario
 */
public class Ventana extends javax.swing.JFrame {
    
    private String ingredientes[]={"chourizo", "jamón", "queso", "morcilla", 
        "champiñon", "lubrigante", "grelos", "piña", "maracuya", "chistorra", 
        "polbo","lechuga","bacon","aceitunas","atun","pollo"};
    private double precioIngre[]={0.1,0.5,0.1,0.2,0.1,2,0.25,0.4,0.6,0.2,1,0.2,0.2,0,1,0.25,0.2};
    private String masas[]={"hiperextramegafina", "hipermegafina", "extrahiperfina", 
        "megaextrafina", "extrafina", "megafina", "hiperfina", "fina"};
    private double precioMasa[]={0.1,0.2,0.25,0.3,0.35,0.4,0.45,0.5};
    private String descuento[]={"50","20","10","5"};
    public static Pedido pedido;
   

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        for(int contador=0;contador<masas.length;contador++){
            cbxMasa.addItem(masas[contador]);
        }
        Component[] componentes=pnPrincipal.getComponents();
        int contIngre=0;
        for(int contador=0;contador<componentes.length;contador++){
            if(componentes[contador] instanceof JCheckBox){
                ((JCheckBox)componentes[contador]).setText(ingredientes[contIngre]);
                contIngre++;
            }            
        }
        for(int contador=0;contador<descuento.length;contador++){
            cbxDescuento.addItem(descuento[contador]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgEntrega = new javax.swing.ButtonGroup();
        pnPrincipal = new javax.swing.JPanel();
        lblDescuento = new javax.swing.JLabel();
        cbxDescuento = new javax.swing.JComboBox<>();
        cbxMasa = new javax.swing.JComboBox<>();
        lblMasa = new javax.swing.JLabel();
        lblEntrega = new javax.swing.JLabel();
        rbLocal = new javax.swing.JRadioButton();
        rbDomicilio = new javax.swing.JRadioButton();
        txfCliente = new javax.swing.JTextField();
        lblCliente = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txfDireccion = new javax.swing.JTextField();
        chb01 = new javax.swing.JCheckBox();
        chb02 = new javax.swing.JCheckBox();
        chb03 = new javax.swing.JCheckBox();
        chb04 = new javax.swing.JCheckBox();
        chb05 = new javax.swing.JCheckBox();
        chb06 = new javax.swing.JCheckBox();
        chb07 = new javax.swing.JCheckBox();
        chb08 = new javax.swing.JCheckBox();
        chb09 = new javax.swing.JCheckBox();
        chb10 = new javax.swing.JCheckBox();
        chb11 = new javax.swing.JCheckBox();
        chb12 = new javax.swing.JCheckBox();
        chb13 = new javax.swing.JCheckBox();
        chb14 = new javax.swing.JCheckBox();
        chb15 = new javax.swing.JCheckBox();
        chb16 = new javax.swing.JCheckBox();
        btPedido = new javax.swing.JButton();
        btnMostrar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDescuento.setText("Descuento:");

        lblMasa.setText("Masa:");

        lblEntrega.setText("Forma de entrega");

        btgEntrega.add(rbLocal);
        rbLocal.setSelected(true);
        rbLocal.setText("En local");
        rbLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLocalActionPerformed(evt);
            }
        });

        btgEntrega.add(rbDomicilio);
        rbDomicilio.setText("En domicilio");
        rbDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDomicilioActionPerformed(evt);
            }
        });

        txfCliente.setEnabled(false);

        lblCliente.setText("Cliente:");
        lblCliente.setEnabled(false);

        lblDireccion.setText("Direccion:");
        lblDireccion.setEnabled(false);

        txfDireccion.setEnabled(false);

        btPedido.setText("HACER PEDIDO");
        btPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPedidoActionPerformed(evt);
            }
        });

        btnMostrar2.setText("MOSTRAR");
        btnMostrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPrincipalLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbLocal)
                            .addComponent(lblEntrega))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbDomicilio)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnPrincipalLayout.createSequentialGroup()
                        .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnPrincipalLayout.createSequentialGroup()
                                .addComponent(chb15, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chb16, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnPrincipalLayout.createSequentialGroup()
                                .addComponent(chb07, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chb12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnPrincipalLayout.createSequentialGroup()
                                .addComponent(chb08, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chb11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnPrincipalLayout.createSequentialGroup()
                                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDireccion)
                                    .addComponent(lblCliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfDireccion)
                                    .addComponent(txfCliente, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(pnPrincipalLayout.createSequentialGroup()
                                .addComponent(chb03, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chb04, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnPrincipalLayout.createSequentialGroup()
                                .addComponent(chb05, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chb06, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnPrincipalLayout.createSequentialGroup()
                                .addComponent(chb09, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chb10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnPrincipalLayout.createSequentialGroup()
                                .addComponent(lblDescuento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnPrincipalLayout.createSequentialGroup()
                                .addComponent(chb13, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chb14, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnPrincipalLayout.createSequentialGroup()
                                .addComponent(chb01, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chb02, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnPrincipalLayout.createSequentialGroup()
                                .addComponent(lblMasa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxMasa, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPrincipalLayout.createSequentialGroup()
                .addComponent(btPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMasa)
                    .addComponent(cbxMasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chb01)
                    .addComponent(chb02))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chb03)
                    .addComponent(chb04))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chb05)
                    .addComponent(chb06))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chb09)
                    .addComponent(chb10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chb08)
                    .addComponent(chb11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chb07)
                    .addComponent(chb12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chb13)
                    .addComponent(chb14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chb15)
                    .addComponent(chb16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescuento)
                    .addComponent(cbxDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblEntrega)
                .addGap(18, 18, 18)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbLocal)
                    .addComponent(rbDomicilio))
                .addGap(18, 18, 18)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCliente))
                .addGap(18, 18, 18)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPedido)
                    .addComponent(btnMostrar2)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLocalActionPerformed
        txfCliente.setEnabled(false);
        lblCliente.setEnabled(false);
        txfDireccion.setEnabled(false);
        lblDireccion.setEnabled(false);
    }//GEN-LAST:event_rbLocalActionPerformed

    private void rbDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDomicilioActionPerformed
        txfCliente.setEnabled(true);
        lblCliente.setEnabled(true);
        txfDireccion.setEnabled(true);
        lblDireccion.setEnabled(true);
    }//GEN-LAST:event_rbDomicilioActionPerformed

    private void btPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPedidoActionPerformed
        String masa=cbxMasa.getSelectedItem().toString();
        String[] ingre=new String[ingredientes.length];
        int contIngre=0;
        Component[] componentes=pnPrincipal.getComponents();
        for(int contador=0;contador<componentes.length;contador++){
            if(componentes[contador] instanceof JCheckBox){
                if(((JCheckBox)componentes[contador]).isSelected()){
                    ingre[contIngre]=((JCheckBox)componentes[contador]).getText();
                }       
            }            
        }
        String descuento=cbxDescuento.getSelectedItem().toString();
        String entrega;
        String cliente="";
        String direccion="";
        if(rbDomicilio.isSelected()){
            entrega="Domicilio";
            cliente=txfCliente.getText();
            direccion=txfDireccion.getText();
        }else
        {
            entrega="Local";
        }
        double precio=0;
        precio+=precioMasa[cbxMasa.getSelectedIndex()];
        for(int contador=0;contador<ingre.length;contador++){
            precio+=precioIngre[Arrays.binarySearch(ingredientes, ingre[contador])];
        }
        precio-=precio*(Integer.parseInt(descuento)*100);
        
        pedido=new Pedido(masa,ingre,descuento,entrega);
        if(entrega.equalsIgnoreCase("Domicilio")){
            pedido.setCliente(cliente);
            pedido.setDireccion(direccion);
        }
        pedido.setPrecio(precio);
    }//GEN-LAST:event_btPedidoActionPerformed

    private void btnMostrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrar2ActionPerformed
        Mostrar mostrar=new Mostrar();
        mostrar.setVisible(true);
    }//GEN-LAST:event_btnMostrar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPedido;
    private javax.swing.ButtonGroup btgEntrega;
    private javax.swing.JButton btnMostrar2;
    private javax.swing.JComboBox<String> cbxDescuento;
    private javax.swing.JComboBox<String> cbxMasa;
    private javax.swing.JCheckBox chb01;
    private javax.swing.JCheckBox chb02;
    private javax.swing.JCheckBox chb03;
    private javax.swing.JCheckBox chb04;
    private javax.swing.JCheckBox chb05;
    private javax.swing.JCheckBox chb06;
    private javax.swing.JCheckBox chb07;
    private javax.swing.JCheckBox chb08;
    private javax.swing.JCheckBox chb09;
    private javax.swing.JCheckBox chb10;
    private javax.swing.JCheckBox chb11;
    private javax.swing.JCheckBox chb12;
    private javax.swing.JCheckBox chb13;
    private javax.swing.JCheckBox chb14;
    private javax.swing.JCheckBox chb15;
    private javax.swing.JCheckBox chb16;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEntrega;
    private javax.swing.JLabel lblMasa;
    private javax.swing.JPanel pnPrincipal;
    private javax.swing.JRadioButton rbDomicilio;
    private javax.swing.JRadioButton rbLocal;
    private javax.swing.JTextField txfCliente;
    private javax.swing.JTextField txfDireccion;
    // End of variables declaration//GEN-END:variables
}
