/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ivamova.guiventana4;

/**
 *
 * @author Usuario
 */
public class Ventana4 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana4
     */
    public Ventana4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstOpciones = new javax.swing.JList<>();
        lblGeneral = new javax.swing.JLabel();
        separador1 = new javax.swing.JSeparator();
        lblEstilo = new javax.swing.JLabel();
        cbEstilo = new javax.swing.JComboBox<>();
        lblVisualizacion = new javax.swing.JLabel();
        chbVer = new javax.swing.JCheckBox();
        chbInteractivo = new javax.swing.JCheckBox();
        chbEditable = new javax.swing.JCheckBox();
        chbVisualFlash = new javax.swing.JCheckBox();
        lblExportacion = new javax.swing.JLabel();
        chbPDF = new javax.swing.JCheckBox();
        chbExcel = new javax.swing.JCheckBox();
        chbHTML = new javax.swing.JCheckBox();
        chbExporFlash = new javax.swing.JCheckBox();
        lblEjecutar = new javax.swing.JLabel();
        cbEjecutar = new javax.swing.JComboBox<>();
        chbPantallaCompleta = new javax.swing.JCheckBox();
        chbBarraFlotante = new javax.swing.JCheckBox();
        chbEnviar = new javax.swing.JCheckBox();
        lblAncho = new javax.swing.JLabel();
        cbAncho = new javax.swing.JComboBox<>();
        lblFormato = new javax.swing.JLabel();
        separator2 = new javax.swing.JSeparator();
        chbFormato = new javax.swing.JCheckBox();
        lblMarca = new javax.swing.JLabel();
        separator3 = new javax.swing.JSeparator();
        btFormato = new javax.swing.JButton();
        btAyuda = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(lstOpciones);

        lblGeneral.setText("General");

        lblEstilo.setText("Estilo automático de cuadrícula por defecto:");

        cbEstilo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pasteles", "Item 2", "Item 3", "Item 4" }));
        cbEstilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstiloActionPerformed(evt);
            }
        });

        lblVisualizacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblVisualizacion.setText("Modos de visualización disponible");
        lblVisualizacion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblVisualizacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblVisualizacion.setName("lblVisualizacion"); // NOI18N

        chbVer.setSelected(true);
        chbVer.setText("Ver");

        chbInteractivo.setSelected(true);
        chbInteractivo.setText("Interactivo");
        chbInteractivo.setEnabled(false);

        chbEditable.setSelected(true);
        chbEditable.setText("Editable");

        chbVisualFlash.setSelected(true);
        chbVisualFlash.setText("Flash");

        lblExportacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblExportacion.setText("Formato de exportación disponibles:");
        lblExportacion.setToolTipText("");
        lblExportacion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblExportacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblExportacion.setName("lblVisualizacion"); // NOI18N

        chbPDF.setSelected(true);
        chbPDF.setText("PDF");

        chbExcel.setSelected(true);
        chbExcel.setText("Excel");

        chbHTML.setSelected(true);
        chbHTML.setText("HTML");

        chbExporFlash.setSelected(true);
        chbExporFlash.setText("Flash");

        lblEjecutar.setText("Por defecto, ejecutar como:");

        cbEjecutar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Interactivo", "Item 2", "Item 3", "Item 4" }));

        chbPantallaCompleta.setSelected(true);
        chbPantallaCompleta.setText("Abrir siempre este documento en modo pantalla completa");

        chbBarraFlotante.setSelected(true);
        chbBarraFlotante.setText("Mostrar barras de herramientas flotantes en Flash");

        chbEnviar.setSelected(true);
        chbEnviar.setText("Enviar automáticamente");

        lblAncho.setText("Modo de ancho de documento:");

        cbAncho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fijo", "Item 2", "Item 3", "Item 4" }));

        lblFormato.setText("Formato condicional");

        chbFormato.setText("Mostrar formato condicional");
        chbFormato.setEnabled(false);

        lblMarca.setText("Marca de agua");

        btFormato.setText("Formato ...");

        btAyuda.setText("Ayuda");

        btCancelar.setText("Cancelar");

        btAceptar.setText("Aceptar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblEstilo)
                                .addGap(18, 18, 18)
                                .addComponent(cbEstilo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblAncho)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbAncho, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chbVer)
                                            .addComponent(lblVisualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chbInteractivo)
                                            .addComponent(chbEditable)
                                            .addComponent(chbVisualFlash)
                                            .addComponent(lblEjecutar))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(chbPDF)
                                                    .addComponent(lblExportacion, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(chbExcel)
                                                    .addComponent(chbHTML)
                                                    .addComponent(chbExporFlash)))
                                            .addComponent(cbEjecutar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(chbPantallaCompleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chbBarraFlotante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chbEnviar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(54, 54, 54)))
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chbFormato, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblGeneral)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(separador1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMarca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(separator3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFormato)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btFormato)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAceptar)
                .addGap(18, 18, 18)
                .addComponent(btCancelar)
                .addGap(18, 18, 18)
                .addComponent(btAyuda)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGeneral))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstilo)
                            .addComponent(cbEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblVisualizacion)
                                .addGap(18, 18, 18)
                                .addComponent(chbVer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbInteractivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbEditable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbVisualFlash))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblExportacion)
                                .addGap(18, 18, 18)
                                .addComponent(chbPDF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbExcel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbHTML)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbExporFlash)))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEjecutar)
                            .addComponent(cbEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(chbPantallaCompleta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbBarraFlotante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbEnviar)
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAncho)
                            .addComponent(cbAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFormato)
                            .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(chbFormato)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMarca)
                            .addComponent(separator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btFormato))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAyuda)
                    .addComponent(btCancelar)
                    .addComponent(btAceptar))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbEstiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstiloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEstiloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceptar;
    private javax.swing.JButton btAyuda;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btFormato;
    private javax.swing.JComboBox<String> cbAncho;
    private javax.swing.JComboBox<String> cbEjecutar;
    private javax.swing.JComboBox<String> cbEstilo;
    private javax.swing.JCheckBox chbBarraFlotante;
    private javax.swing.JCheckBox chbEditable;
    private javax.swing.JCheckBox chbEnviar;
    private javax.swing.JCheckBox chbExcel;
    private javax.swing.JCheckBox chbExporFlash;
    private javax.swing.JCheckBox chbFormato;
    private javax.swing.JCheckBox chbHTML;
    private javax.swing.JCheckBox chbInteractivo;
    private javax.swing.JCheckBox chbPDF;
    private javax.swing.JCheckBox chbPantallaCompleta;
    private javax.swing.JCheckBox chbVer;
    private javax.swing.JCheckBox chbVisualFlash;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAncho;
    private javax.swing.JLabel lblEjecutar;
    private javax.swing.JLabel lblEstilo;
    private javax.swing.JLabel lblExportacion;
    private javax.swing.JLabel lblFormato;
    private javax.swing.JLabel lblGeneral;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblVisualizacion;
    private javax.swing.JList<String> lstOpciones;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JSeparator separator3;
    // End of variables declaration//GEN-END:variables
}
