/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ifct0609.mavenproject2;

/**
 *
 * @author Usuario
 */
public class Frame4 extends javax.swing.JFrame {

    /**
     * Creates new form Frame4
     */
    public Frame4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaTexto = new javax.swing.JTextArea();
        EtiquetaGeneral = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        ComboBoxEstilos = new javax.swing.JComboBox<>();
        EitquetaModos = new javax.swing.JLabel();
        EitquetaFormatos = new javax.swing.JLabel();
        CheckBoxVer = new javax.swing.JCheckBox();
        CheckBoxInteractivo = new javax.swing.JCheckBox();
        CheckBoxEditable = new javax.swing.JCheckBox();
        CheckBoxFlash = new javax.swing.JCheckBox();
        ButtonAceptar = new javax.swing.JButton();
        ButtonCancelar = new javax.swing.JButton();
        ButtonAplicar = new javax.swing.JButton();
        CheckBoxPdf = new javax.swing.JCheckBox();
        CheckBoxExcel = new javax.swing.JCheckBox();
        CheckBoxHtml = new javax.swing.JCheckBox();
        CheckBoxFormatoFlash = new javax.swing.JCheckBox();
        LabelPorDefecto = new javax.swing.JLabel();
        ComboBoxEjecucionDefecto = new javax.swing.JComboBox<>();
        CheckBoxPantallaCompleta = new javax.swing.JCheckBox();
        CheckBoxBarraFlash = new javax.swing.JCheckBox();
        CheckBoxEnviar = new javax.swing.JCheckBox();
        EitquetaModosAncho = new javax.swing.JLabel();
        ComboBoxModoAncho = new javax.swing.JComboBox<>();
        EtiquetaCondicional = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        CheckBoxMostrarFormato = new javax.swing.JCheckBox();
        EtiquetaMarcaAgua = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        ButtonFormatoAgua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AreaTexto.setColumns(20);
        AreaTexto.setRows(5);
        jScrollPane1.setViewportView(AreaTexto);

        EtiquetaGeneral.setText("General");

        jLabel1.setText("Estilo automático de cuadrícula por defecto: ");

        ComboBoxEstilos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pasteles", "Item 1", "Item 2", "Item 3", "Item 4" }));

        EitquetaModos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EitquetaModos.setText("<html>Modos de visualización disponibles:<html>");
        EitquetaModos.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        EitquetaModos.setAutoscrolls(true);
        EitquetaModos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EitquetaModos.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        EitquetaFormatos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EitquetaFormatos.setText("<html>Formatos de exportación disponibles:<html>");
        EitquetaFormatos.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        EitquetaFormatos.setAutoscrolls(true);
        EitquetaFormatos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EitquetaFormatos.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        CheckBoxVer.setSelected(true);
        CheckBoxVer.setText("Ver");

        CheckBoxInteractivo.setSelected(true);
        CheckBoxInteractivo.setText("Interactivo");
        CheckBoxInteractivo.setEnabled(false);

        CheckBoxEditable.setSelected(true);
        CheckBoxEditable.setText("Editable");
        CheckBoxEditable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxEditableActionPerformed(evt);
            }
        });

        CheckBoxFlash.setSelected(true);
        CheckBoxFlash.setText("Flash");

        ButtonAceptar.setText("Aceptar");

        ButtonCancelar.setText("Cancelar");

        ButtonAplicar.setText("Aplicar");

        CheckBoxPdf.setSelected(true);
        CheckBoxPdf.setText("PDF");

        CheckBoxExcel.setSelected(true);
        CheckBoxExcel.setText("Excel");
        CheckBoxExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxExcelActionPerformed(evt);
            }
        });

        CheckBoxHtml.setSelected(true);
        CheckBoxHtml.setText("HTML");

        CheckBoxFormatoFlash.setSelected(true);
        CheckBoxFormatoFlash.setText("Flash");

        LabelPorDefecto.setText("Por defecto, ejecutar como:");

        ComboBoxEjecucionDefecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Interactivo", "Item 1", "Item 2", "Item 3", "Item 4" }));

        CheckBoxPantallaCompleta.setSelected(true);
        CheckBoxPantallaCompleta.setText("<HTML>A<u>b</u>rir siempre este documento en modo de pantalla completa.<HTML>");
        CheckBoxPantallaCompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxPantallaCompletaActionPerformed(evt);
            }
        });

        CheckBoxBarraFlash.setSelected(true);
        CheckBoxBarraFlash.setText("<HTML>Mos<u>t</u>rar barra de herramientas flotantes en Flash.<HTML>");

        CheckBoxEnviar.setSelected(true);
        CheckBoxEnviar.setText("<HTML>Enviar a<u>u</u>tomáticamente.<HTML>");

        EitquetaModosAncho.setText("<HTML><u>M</u>odo de ancho de documento:<HTML>");

        ComboBoxModoAncho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fijo", "Item 1", "Item 2", "Item 3", "Item 4" }));

        EtiquetaCondicional.setText("Formato condicional. ");

        CheckBoxMostrarFormato.setText("Mostrar formato condicional.");
        CheckBoxMostrarFormato.setEnabled(false);

        EtiquetaMarcaAgua.setText("Marca de agua.");

        ButtonFormatoAgua.setText("Formato");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(EtiquetaGeneral)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(EtiquetaMarcaAgua)
                                                .addGap(18, 18, 18)
                                                .addComponent(jSeparator3))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(EtiquetaCondicional)
                                                .addGap(29, 29, 29)
                                                .addComponent(jSeparator2))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(EitquetaModos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(CheckBoxVer)
                                                    .addComponent(CheckBoxInteractivo)
                                                    .addComponent(CheckBoxEditable)
                                                    .addComponent(CheckBoxFlash)
                                                    .addComponent(CheckBoxPantallaCompleta)
                                                    .addComponent(CheckBoxBarraFlash)
                                                    .addComponent(CheckBoxEnviar)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                            .addComponent(EitquetaModosAncho)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(ComboBoxModoAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                            .addComponent(LabelPorDefecto)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(ComboBoxEjecucionDefecto, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(0, 41, Short.MAX_VALUE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(CheckBoxMostrarFormato))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(ButtonFormatoAgua)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonAplicar))
                            .addComponent(ComboBoxEstilos, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EitquetaFormatos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CheckBoxPdf)
                                    .addComponent(CheckBoxExcel)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(CheckBoxFormatoFlash)
                                        .addComponent(CheckBoxHtml)))
                                .addGap(65, 65, 65)))))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonAceptar)
                            .addComponent(ButtonCancelar)
                            .addComponent(ButtonAplicar))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EtiquetaGeneral))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(ComboBoxEstilos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EitquetaFormatos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CheckBoxPdf))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EitquetaModos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CheckBoxVer)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CheckBoxExcel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CheckBoxHtml))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CheckBoxInteractivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CheckBoxEditable)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckBoxFlash)
                            .addComponent(CheckBoxFormatoFlash, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LabelPorDefecto)
                                    .addComponent(ComboBoxEjecucionDefecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CheckBoxPantallaCompleta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CheckBoxBarraFlash)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CheckBoxEnviar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(EitquetaModosAncho)
                                            .addComponent(ComboBoxModoAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EtiquetaCondicional))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CheckBoxMostrarFormato)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EtiquetaMarcaAgua))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonFormatoAgua)
                        .addGap(0, 49, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckBoxPantallaCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxPantallaCompletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxPantallaCompletaActionPerformed

    private void CheckBoxEditableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxEditableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxEditableActionPerformed

    private void CheckBoxExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxExcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaTexto;
    private javax.swing.JButton ButtonAceptar;
    private javax.swing.JButton ButtonAplicar;
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonFormatoAgua;
    private javax.swing.JCheckBox CheckBoxBarraFlash;
    private javax.swing.JCheckBox CheckBoxEditable;
    private javax.swing.JCheckBox CheckBoxEnviar;
    private javax.swing.JCheckBox CheckBoxExcel;
    private javax.swing.JCheckBox CheckBoxFlash;
    private javax.swing.JCheckBox CheckBoxFormatoFlash;
    private javax.swing.JCheckBox CheckBoxHtml;
    private javax.swing.JCheckBox CheckBoxInteractivo;
    private javax.swing.JCheckBox CheckBoxMostrarFormato;
    private javax.swing.JCheckBox CheckBoxPantallaCompleta;
    private javax.swing.JCheckBox CheckBoxPdf;
    private javax.swing.JCheckBox CheckBoxVer;
    private javax.swing.JComboBox<String> ComboBoxEjecucionDefecto;
    private javax.swing.JComboBox<String> ComboBoxEstilos;
    private javax.swing.JComboBox<String> ComboBoxModoAncho;
    private javax.swing.JLabel EitquetaFormatos;
    private javax.swing.JLabel EitquetaModos;
    private javax.swing.JLabel EitquetaModosAncho;
    private javax.swing.JLabel EtiquetaCondicional;
    private javax.swing.JLabel EtiquetaGeneral;
    private javax.swing.JLabel EtiquetaMarcaAgua;
    private javax.swing.JLabel LabelPorDefecto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
