all: client0.c server0.c server1.c client1.c client2.c server2.c
	gcc client0.c -o client0.o
	gcc server0.c -o server0.o
	gcc server1.c -o server1.o
	gcc client1.c -o client1.o
	gcc client2.c -o client2.o
	gcc server2.c -o server2.o
clean:
	rm *.o
