build: 1 2 3 4 5 6
1:
	make build -C 1
2:
	make build -C 2
3:
	make build -C 3
4:
	make build -C 4
5:
	make build -C 5
6:
	make build -C 6
clean: 1c 2c 3c 4c 5c 6c
1c:
	make clean -C 1 -i
2c:
	make clean -C 2 -i
3c:
	make clean -C 3 -i
4c:
	make clean -C 4 -i
5c:
	make clean -C 5 -i
6c:
	make clean -C 6 -i
