threads00: threads00.c
	gcc -o threads00.out threads00.c -lpthread
threads01: threads01.c
	gcc -o threads01.out threads01.c -lpthread
threads02: threads02.c
	gcc -o threads02.out threads02.c -lpthread
threads03: threads03.c
	gcc -o threads03.out threads03.c -lpthread
threads04: threads04.c
	gcc -o threads04.out threads04.c -lpthread
threads05: threads05.c
	gcc -o threads05.out threads05.c -lpthread
threads06: threads06.c
	gcc -o threads06.out threads06.c -lpthread
threads07: threads07.c
	gcc -o threads07.out threads07.c -lpthread
threads08: threads08.c
	gcc -o threads08.out threads08.c -lpthread -lm
threads09: threads09.c
	gcc -o threads09.out threads09.c -lpthread
threads10-1: threads10-1.c
	gcc -o threads10-1.out threads10-1.c -lpthread
threads10-2: threads10-2.c
	gcc -o threads10-2.out threads10-2.c -lpthread
threads10-3: threads10-3.c
	gcc -o threads10-3.out threads10-3.c -lpthread
threads10-4: threads10-4.c
	gcc -o threads10-4.out threads10-4.c -lpthread
threads11: threads11.c
	gcc -o threads11.out threads11.c -lpthread -lm

all: threads00 threads01 threads02 threads03 threads04 threads05 threads06 threads07 threads08 threads09 threads10-1 threads10-2 threads10-3 threads10-4 threads11

clean:
	rm *.out
