all: ex ex2 ex2.4 ex3

ex: execprog1.c
	gcc execprog1.c -o execprog1.out

ex2: execprog2.c
	gcc execprog2.c -o execprog2.out

ex2.4: execprog2.4.c
	gcc execprog2.4.c -o execprog2.4.out

ex3: execprog3.c
	gcc execprog3.c -o execprog3.out

clean:
	rm execprog*.out
