build: build_1 build_2 build_3 build_4
build_1:
	make build -C 1
build_2:
	make build -C 2
build_3:
	make build -C 3
build_4:
	make build -C 4
clean: clean_1 clean_2 clean_3 clean_4
clean_1:
	make clean -C 1 -i
clean_2:
	make clean -C 2 -i
clean_3:
	make clean -C 3 -i
clean_4:
	make clean -C 4 -i
