/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebas_programacion_java.copiadearchivo;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
/**
 *
 * @author Usuario
 */
public class Copia extends javax.swing.JFrame {

    /**
     * Creates new form Copia
     */
    public Copia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TFnombreDeArchivo = new javax.swing.JTextField();
        TFrutaArchivo = new javax.swing.JTextField();
        TFcopia = new javax.swing.JTextField();
        TFrutaDestino = new javax.swing.JTextField();
        Bcopiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Copia");

        TFnombreDeArchivo.setText("Introducca el nombre del archivo");
        TFnombreDeArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TFnombreDeArchivoMouseReleased(evt);
            }
        });

        TFrutaArchivo.setText("Introducca la ruta del archivo");
        TFrutaArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TFrutaArchivoMouseReleased(evt);
            }
        });

        TFcopia.setText("Introducca el nombre de la copia ");
        TFcopia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TFcopiaMouseReleased(evt);
            }
        });

        TFrutaDestino.setText("Introducca la ruta de destino");
        TFrutaDestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TFrutaDestinoMouseReleased(evt);
            }
        });

        Bcopiar.setText("Copiar");
        Bcopiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BcopiarMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFnombreDeArchivo)
                            .addComponent(TFrutaArchivo)
                            .addComponent(TFcopia, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(TFrutaDestino)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(Bcopiar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TFnombreDeArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFrutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFcopia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFrutaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Bcopiar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BcopiarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BcopiarMouseReleased
        String original;
        String copia;
        String temp;
        original=TFrutaArchivo.getText()+TFnombreDeArchivo.getText();
        copia=TFrutaDestino.getText()+TFcopia.getText();
        
        try{
            FileReader lectura = new FileReader(original);
            FileWriter escritura = new FileWriter(copia);
        
            BufferedReader in = new BufferedReader(lectura);
            BufferedWriter out = new BufferedWriter(escritura);
            
            while((temp = in.readLine()) != null){
                
                out.write(temp);
            }
            
            in.close();
            out.close();
            
        }catch(IOException e){
            System.out.println("Error E/S: " +e);}
    }//GEN-LAST:event_BcopiarMouseReleased

    private void TFnombreDeArchivoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFnombreDeArchivoMouseReleased
        TFnombreDeArchivo.setText("");
    }//GEN-LAST:event_TFnombreDeArchivoMouseReleased

    private void TFrutaArchivoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFrutaArchivoMouseReleased
        TFrutaArchivo.setText("");
    }//GEN-LAST:event_TFrutaArchivoMouseReleased

    private void TFcopiaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFcopiaMouseReleased
        TFcopia.setText("");
    }//GEN-LAST:event_TFcopiaMouseReleased

    private void TFrutaDestinoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFrutaDestinoMouseReleased
        TFrutaDestino.setText("");
    }//GEN-LAST:event_TFrutaDestinoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Copia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Copia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Copia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Copia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Copia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcopiar;
    private javax.swing.JTextField TFcopia;
    private javax.swing.JTextField TFnombreDeArchivo;
    private javax.swing.JTextField TFrutaArchivo;
    private javax.swing.JTextField TFrutaDestino;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
