/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gozerelgozeriano.webbrowser;
//import chrriis.dj.nativeswing.*;
//import chrriis.common.*;
//import chrriis.common.UIUtils;
import chrriis.common.UIUtils;
import chrriis.dj.nativeswing.NSComponentOptions;
import chrriis.dj.nativeswing.NativeSwing;
import chrriis.dj.nativeswing.swtimpl.NativeInterface;
//import chrriis.dj.nativeswing.swtimpl.NativeInterface;
import java.awt.BorderLayout;
import javax.swing.JFrame;
//import javax.swing.JFrame;
//import javax.swing.SwingUtilities;

/**
 *
 * @author Usuario
 */
public class mainframe extends javax.swing.JFrame {

    /**
     * Creates new form mainframe
     */
    public mainframe() {
        initComponents();
        //loadWebBrowser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadWebBrowser(){
        
        WebBrowser = new chrriis.dj.nativeswing.swtimpl.components.JWebBrowser();
        WebBrowser.setBarsVisible(false);
        WebBrowser.setStatusBarVisible(false);
        WebBrowser.setDefaultPopupMenuRegistered(false);
        WebBrowser.setJavascriptEnabled(true);
        WebBrowser.setDoubleBuffered(true);
        WebBrowser.getNativeComponent().createBackBuffer();
        WebBrowser.navigate("www.google.com");
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        add(WebBrowser,BorderLayout.CENTER );
    }
    
    


    public NavigationControl NC;
    public static chrriis.dj.nativeswing.swtimpl.components.JWebBrowser WebBrowser;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
