aux-func1: aux-func1.c
	gcc -o aux-func1.out aux-func1.c
aux-func2: aux-func2.c
	gcc -o aux-func2.out aux-func2.c
aux-func3: aux-func3.c
	gcc -o aux-func3.out aux-func3.c
process01: process01.c
	gcc -o process01.out process01.c
process02: process02.c
	gcc -o process02.out process02.c
process03: process03.c
	gcc -o process03.out process03.c
process04: process04.c
	gcc -o process04.out process04.c 

all: aux-func1 aux-func2 aux-func3 process01 process02 process03 process04

clean:
	rm *.out
