all: 1_electrodomesticos.cpp lib/nevera.h lib/lavadora.h lib/radiador.h 2_notas.cpp lib/ciencias.h lib/asignatura.h lib/letras.h lib/musica.h lib/tecnologia.h
	g++ 2_notas.cpp -o notas.o
	g++ 1_electrodomesticos.cpp -o electrodomesticos.o
clean:
	rm -f *.o
