all: bmpheader.c execprog1.c execprog2.c fork.c kamelot.c tachenkos.c
	gcc bmpheader.c -o bmpheader.o
	gcc execprog1.c -o execprog2.c
	gcc fork.c -o fork.o
	gcc kamelot.c -o kamelot.o
	gcc tachenkos.c -o tachenkos.o

clean:
	rm *.o
