/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//TODO Convertir los menus de seleccion de hardcoded a generados
package com.mycompany.functionalguis;

import java.util.HashMap;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Usuario
 */
public class Pizza extends javax.swing.JFrame {
    
    JRadioButton[] RdoBases;
    JCheckBox[] ChkIngredientes;
    JRadioButton[] RdoDescue;
    final String DefaultIngreSummary = "No ha seleccionado";
    String TicketDatosPizza;
    String TicketDatosDescue;
    String TicketDatosDireccion;
    String TicketMonto;
    HashMap<String, Float> PreciosBases;
    HashMap<String, Float> PreciosIngre;
    Float Descuento = 1.0f;
    /**
     * Creates new form Pizza
     */
    public Pizza() {
        setLocationRelativeTo(null);
        initComponents();
        
        RdoBases = new JRadioButton[] {
            RdoFina,
            RdoHiperfina,
            RdoMegafauna,
            RdoExtrafina,
            RdoMegaextrafina,
            RdoExtrahiperfina,
            RdoHipermegafina,
            RdoHiperextramegafina,
        };
        ChkIngredientes = new JCheckBox[] {
            ChkChorizo,
            ChkJamon,
            ChkQueso,
            ChkMorcilla,
            ChkChampiñon,
            ChkLubrigante,
            ChkGrelos,
            ChkPiña,
            ChkMaracuya,
            ChkChistorra,
            ChkPollo,
        };
        RdoDescue = new JRadioButton[] {
            RdoCeroPor,
            RdoDiezPor,
            RdoVeintePor,
            RdoVeinticincoPor,
        };
        PreciosBases = new HashMap<String, Float>() {
            {
                put("Fina", 1.00f);
                put("Hiperfina", 2.00f);
                put("Megafina", 3.00f);
                put("Extrafina", 4.00f);
                put("Megaextrafina", 5.00f);
                put("Extrahiperfina", 6.00f);
                put("Hipermegafina", 7.00f);
                put("Hiperextramegafina", 8.00f);
            }
        };
        PreciosIngre = new HashMap<String, Float>() {
            {
                put("Chorizo", 0.33f);
                put("Jamon", 0.33f);
                put("Queso", 0.33f);
                put("Morcilla", 0.33f);
                put("Champiñon", 0.33f);
                put("Lubrigante", 0.33f);
                put("Grelos", 0.33f);
                put("Piña", 0.33f);
                put("Maracuya", 0.33f);
                put("Chistorra", 0.33f);
                put("Pollo", 0.33f);
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtngrpBases = new javax.swing.ButtonGroup();
        BtngrpDescue = new javax.swing.ButtonGroup();
        FrameBases = new javax.swing.JFrame();
        PanelBases = new javax.swing.JPanel();
        LblBasesTitulo = new javax.swing.JLabel();
        RdoFina = new javax.swing.JRadioButton();
        RdoHiperfina = new javax.swing.JRadioButton();
        RdoMegafauna = new javax.swing.JRadioButton();
        RdoExtrafina = new javax.swing.JRadioButton();
        RdoMegaextrafina = new javax.swing.JRadioButton();
        RdoExtrahiperfina = new javax.swing.JRadioButton();
        RdoHipermegafina = new javax.swing.JRadioButton();
        RdoHiperextramegafina = new javax.swing.JRadioButton();
        FrameIngredientes = new javax.swing.JFrame();
        PanelIngredientes = new javax.swing.JPanel();
        LblIngreTitulo = new javax.swing.JLabel();
        ChkChorizo = new javax.swing.JCheckBox();
        ChkJamon = new javax.swing.JCheckBox();
        ChkQueso = new javax.swing.JCheckBox();
        ChkLubrigante = new javax.swing.JCheckBox();
        ChkMorcilla = new javax.swing.JCheckBox();
        ChkChampiñon = new javax.swing.JCheckBox();
        ChkMaracuya = new javax.swing.JCheckBox();
        ChkGrelos = new javax.swing.JCheckBox();
        ChkPiña = new javax.swing.JCheckBox();
        ChkChistorra = new javax.swing.JCheckBox();
        ChkPollo = new javax.swing.JCheckBox();
        FrameTicket = new javax.swing.JFrame();
        PanelTicket = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaTicket = new javax.swing.JTextArea();
        PanelPrincipal = new javax.swing.JPanel();
        PanelPedido = new javax.swing.JPanel();
        BtnEscogerBase = new javax.swing.JButton();
        BtnEscogerIngre = new javax.swing.JButton();
        ChkBase = new javax.swing.JCheckBox();
        ChkIngre = new javax.swing.JCheckBox();
        LblBase = new javax.swing.JLabel();
        LblIngredientes = new javax.swing.JLabel();
        LblTitulo = new javax.swing.JLabel();
        LblListaBase = new javax.swing.JLabel();
        LblListaIngre = new javax.swing.JLabel();
        PanelDescuentos = new javax.swing.JPanel();
        LabelDescuentos = new javax.swing.JLabel();
        RdoCeroPor = new javax.swing.JRadioButton();
        RdoDiezPor = new javax.swing.JRadioButton();
        RdoVeintePor = new javax.swing.JRadioButton();
        RdoVeinticincoPor = new javax.swing.JRadioButton();
        FieldCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        PanelDatosDomicilio = new javax.swing.JPanel();
        LblNombre = new javax.swing.JLabel();
        LblDireccion = new javax.swing.JLabel();
        FieldNombre = new javax.swing.JTextField();
        FieldDireccion1 = new javax.swing.JTextField();
        RdoDomicilio = new javax.swing.JRadioButton();
        FieldDireccion2 = new javax.swing.JTextField();
        PanelComprar = new javax.swing.JPanel();
        BtnComprar = new javax.swing.JButton();
        LblPrecio = new javax.swing.JLabel();

        FrameBases.setTitle("Bases");

        LblBasesTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LblBasesTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblBasesTitulo.setText("Escoga su base preferida");

        BtngrpBases.add(RdoFina);
        RdoFina.setText("Fina");
        RdoFina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RdoFinaMouseReleased(evt);
            }
        });

        BtngrpBases.add(RdoHiperfina);
        RdoHiperfina.setText("Hiperfina");
        RdoHiperfina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RdoHiperfinaMouseReleased(evt);
            }
        });

        BtngrpBases.add(RdoMegafauna);
        RdoMegafauna.setText("Megafina");
        RdoMegafauna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RdoMegafaunaMouseReleased(evt);
            }
        });

        BtngrpBases.add(RdoExtrafina);
        RdoExtrafina.setText("Extrafina");
        RdoExtrafina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RdoExtrafinaMouseReleased(evt);
            }
        });

        BtngrpBases.add(RdoMegaextrafina);
        RdoMegaextrafina.setText("Megaextrafina");
        RdoMegaextrafina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RdoMegaextrafinaMouseReleased(evt);
            }
        });

        BtngrpBases.add(RdoExtrahiperfina);
        RdoExtrahiperfina.setText("Extrahiperfina");
        RdoExtrahiperfina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RdoExtrahiperfinaMouseReleased(evt);
            }
        });

        BtngrpBases.add(RdoHipermegafina);
        RdoHipermegafina.setText("Hipermegafina");
        RdoHipermegafina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RdoHipermegafinaMouseReleased(evt);
            }
        });

        BtngrpBases.add(RdoHiperextramegafina);
        RdoHiperextramegafina.setText("Hiperextramegafina");
        RdoHiperextramegafina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RdoHiperextramegafinaMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout PanelBasesLayout = new javax.swing.GroupLayout(PanelBases);
        PanelBases.setLayout(PanelBasesLayout);
        PanelBasesLayout.setHorizontalGroup(
            PanelBasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBasesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RdoHiperextramegafina)
                    .addComponent(RdoHipermegafina)
                    .addComponent(RdoExtrahiperfina)
                    .addComponent(RdoMegaextrafina)
                    .addComponent(RdoExtrafina)
                    .addComponent(RdoMegafauna)
                    .addComponent(RdoHiperfina)
                    .addComponent(RdoFina)
                    .addComponent(LblBasesTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelBasesLayout.setVerticalGroup(
            PanelBasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBasesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblBasesTitulo)
                .addGap(18, 18, 18)
                .addComponent(RdoFina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RdoHiperfina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RdoMegafauna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RdoExtrafina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RdoMegaextrafina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RdoExtrahiperfina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RdoHipermegafina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RdoHiperextramegafina)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FrameBasesLayout = new javax.swing.GroupLayout(FrameBases.getContentPane());
        FrameBases.getContentPane().setLayout(FrameBasesLayout);
        FrameBasesLayout.setHorizontalGroup(
            FrameBasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FrameBasesLayout.setVerticalGroup(
            FrameBasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        FrameIngredientes.setTitle("Ingredientes");

        LblIngreTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LblIngreTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblIngreTitulo.setText("Escoga sus ingredientes");

        ChkChorizo.setText("Chorizo");
        ChkChorizo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ChkChorizoMouseReleased(evt);
            }
        });

        ChkJamon.setText("Jamon");
        ChkJamon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ChkJamonMouseReleased(evt);
            }
        });

        ChkQueso.setText("Queso");
        ChkQueso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ChkQuesoMouseReleased(evt);
            }
        });

        ChkLubrigante.setText("Lubrigante");
        ChkLubrigante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ChkLubriganteMouseReleased(evt);
            }
        });

        ChkMorcilla.setText("Morcilla");
        ChkMorcilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ChkMorcillaMouseReleased(evt);
            }
        });

        ChkChampiñon.setText("Champiñon");
        ChkChampiñon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ChkChampiñonMouseReleased(evt);
            }
        });

        ChkMaracuya.setText("Maracuya");
        ChkMaracuya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ChkMaracuyaMouseReleased(evt);
            }
        });

        ChkGrelos.setText("Grelos");
        ChkGrelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ChkGrelosMouseReleased(evt);
            }
        });

        ChkPiña.setText("Piña");
        ChkPiña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ChkPiñaMouseReleased(evt);
            }
        });

        ChkChistorra.setText("Chistorra");
        ChkChistorra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ChkChistorraMouseReleased(evt);
            }
        });

        ChkPollo.setText("Pollo");
        ChkPollo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ChkPolloMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout PanelIngredientesLayout = new javax.swing.GroupLayout(PanelIngredientes);
        PanelIngredientes.setLayout(PanelIngredientesLayout);
        PanelIngredientesLayout.setHorizontalGroup(
            PanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIngredientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblIngreTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addGroup(PanelIngredientesLayout.createSequentialGroup()
                        .addGroup(PanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChkPollo)
                            .addComponent(ChkChistorra)
                            .addComponent(ChkMaracuya)
                            .addComponent(ChkPiña)
                            .addComponent(ChkGrelos)
                            .addComponent(ChkLubrigante)
                            .addComponent(ChkChampiñon)
                            .addComponent(ChkMorcilla)
                            .addComponent(ChkQueso)
                            .addComponent(ChkJamon)
                            .addComponent(ChkChorizo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelIngredientesLayout.setVerticalGroup(
            PanelIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIngredientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblIngreTitulo)
                .addGap(18, 18, 18)
                .addComponent(ChkChorizo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChkJamon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChkQueso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChkMorcilla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChkChampiñon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChkLubrigante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChkGrelos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChkPiña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChkMaracuya)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChkChistorra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChkPollo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FrameIngredientesLayout = new javax.swing.GroupLayout(FrameIngredientes.getContentPane());
        FrameIngredientes.getContentPane().setLayout(FrameIngredientesLayout);
        FrameIngredientesLayout.setHorizontalGroup(
            FrameIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        FrameIngredientesLayout.setVerticalGroup(
            FrameIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        FrameTicket.setTitle("Ticket");
        FrameTicket.setType(java.awt.Window.Type.POPUP);

        AreaTicket.setEditable(false);
        AreaTicket.setColumns(20);
        AreaTicket.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        AreaTicket.setLineWrap(true);
        AreaTicket.setRows(5);
        AreaTicket.setText("Base:\n\nIngredientes:\n\nDescuentos:\n\nDireccion de domicilio:\n\nMonto a pagar:\n");
        AreaTicket.setWrapStyleWord(true);
        jScrollPane1.setViewportView(AreaTicket);

        javax.swing.GroupLayout PanelTicketLayout = new javax.swing.GroupLayout(PanelTicket);
        PanelTicket.setLayout(PanelTicketLayout);
        PanelTicketLayout.setHorizontalGroup(
            PanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelTicketLayout.setVerticalGroup(
            PanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout FrameTicketLayout = new javax.swing.GroupLayout(FrameTicket.getContentPane());
        FrameTicket.getContentPane().setLayout(FrameTicketLayout);
        FrameTicketLayout.setHorizontalGroup(
            FrameTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FrameTicketLayout.setVerticalGroup(
            FrameTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TeleSuperPizzaQueLoFlipas");
        setMinimumSize(new java.awt.Dimension(361, 380));

        PanelPedido.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BtnEscogerBase.setText("Escoger...");
        BtnEscogerBase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnEscogerBaseMouseReleased(evt);
            }
        });

        BtnEscogerIngre.setText("Escoger...");
        BtnEscogerIngre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnEscogerIngreMouseReleased(evt);
            }
        });

        ChkBase.setEnabled(false);

        ChkIngre.setEnabled(false);

        LblBase.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LblBase.setText("Base");

        LblIngredientes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LblIngredientes.setText("Ingredientes");

        LblTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo.setText("Cree su pizza");

        LblListaBase.setText("No ha seleccionado");

        LblListaIngre.setText("No ha seleccionado");

        javax.swing.GroupLayout PanelPedidoLayout = new javax.swing.GroupLayout(PanelPedido);
        PanelPedido.setLayout(PanelPedidoLayout);
        PanelPedidoLayout.setHorizontalGroup(
            PanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblBase)
                    .addComponent(LblIngredientes)
                    .addComponent(LblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelPedidoLayout.createSequentialGroup()
                        .addComponent(ChkBase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnEscogerBase))
                    .addComponent(LblListaBase)
                    .addGroup(PanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(LblListaIngre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelPedidoLayout.createSequentialGroup()
                            .addComponent(ChkIngre)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BtnEscogerIngre))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPedidoLayout.setVerticalGroup(
            PanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblBase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ChkBase)
                    .addComponent(BtnEscogerBase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblListaBase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblIngredientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnEscogerIngre)
                    .addComponent(ChkIngre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblListaIngre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelDescuentos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabelDescuentos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelDescuentos.setText("% Descuento");

        BtngrpDescue.add(RdoCeroPor);
        RdoCeroPor.setSelected(true);
        RdoCeroPor.setText("0");
        RdoCeroPor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RdoCeroPorMouseReleased(evt);
            }
        });

        BtngrpDescue.add(RdoDiezPor);
        RdoDiezPor.setText("10");
        RdoDiezPor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RdoDiezPorMouseReleased(evt);
            }
        });

        BtngrpDescue.add(RdoVeintePor);
        RdoVeintePor.setText("20");
        RdoVeintePor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RdoVeintePorMouseReleased(evt);
            }
        });

        BtngrpDescue.add(RdoVeinticincoPor);
        RdoVeinticincoPor.setText("25");
        RdoVeinticincoPor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RdoVeinticincoPorMouseReleased(evt);
            }
        });

        FieldCodigo.setEnabled(false);

        jLabel1.setText("Código:");

        javax.swing.GroupLayout PanelDescuentosLayout = new javax.swing.GroupLayout(PanelDescuentos);
        PanelDescuentos.setLayout(PanelDescuentosLayout);
        PanelDescuentosLayout.setHorizontalGroup(
            PanelDescuentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDescuentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDescuentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RdoDiezPor)
                    .addComponent(RdoVeinticincoPor)
                    .addComponent(RdoCeroPor)
                    .addComponent(LabelDescuentos)
                    .addComponent(RdoVeintePor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDescuentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDescuentosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(FieldCodigo))
                .addContainerGap())
        );
        PanelDescuentosLayout.setVerticalGroup(
            PanelDescuentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDescuentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDescuentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RdoCeroPor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RdoDiezPor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDescuentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RdoVeintePor)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDescuentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RdoVeinticincoPor)
                    .addComponent(FieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelDatosDomicilio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LblNombre.setText("Nombre");
        LblNombre.setEnabled(false);

        LblDireccion.setText("Dirección");
        LblDireccion.setEnabled(false);

        FieldNombre.setEnabled(false);

        FieldDireccion1.setEnabled(false);

        RdoDomicilio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        RdoDomicilio.setText("Pedido a domicilio");
        RdoDomicilio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RdoDomicilioMouseReleased(evt);
            }
        });

        FieldDireccion2.setEnabled(false);

        javax.swing.GroupLayout PanelDatosDomicilioLayout = new javax.swing.GroupLayout(PanelDatosDomicilio);
        PanelDatosDomicilio.setLayout(PanelDatosDomicilioLayout);
        PanelDatosDomicilioLayout.setHorizontalGroup(
            PanelDatosDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosDomicilioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDatosDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosDomicilioLayout.createSequentialGroup()
                        .addComponent(LblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldNombre))
                    .addComponent(FieldDireccion1)
                    .addGroup(PanelDatosDomicilioLayout.createSequentialGroup()
                        .addGroup(PanelDatosDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblDireccion)
                            .addComponent(RdoDomicilio))
                        .addGap(0, 71, Short.MAX_VALUE))
                    .addComponent(FieldDireccion2))
                .addContainerGap())
        );
        PanelDatosDomicilioLayout.setVerticalGroup(
            PanelDatosDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosDomicilioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RdoDomicilio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelDatosDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNombre)
                    .addComponent(FieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FieldDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FieldDireccion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelComprar.setEnabled(false);
        PanelComprar.setMinimumSize(new java.awt.Dimension(100, 416));

        BtnComprar.setText("Comprar ya!");
        BtnComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnComprarMouseReleased(evt);
            }
        });

        LblPrecio.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        LblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblPrecio.setText("0.0");

        javax.swing.GroupLayout PanelComprarLayout = new javax.swing.GroupLayout(PanelComprar);
        PanelComprar.setLayout(PanelComprarLayout);
        PanelComprarLayout.setHorizontalGroup(
            PanelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelComprarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnComprar)
                .addContainerGap())
        );
        PanelComprarLayout.setVerticalGroup(
            PanelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelComprarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PanelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnComprar)
                    .addComponent(LblPrecio)))
        );

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelComprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelDescuentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelDatosDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(PanelDescuentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelDatosDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(PanelComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RdoDomicilioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdoDomicilioMouseReleased
        LblNombre.setEnabled(!LblNombre.isEnabled());
        LblDireccion.setEnabled(!LblDireccion.isEnabled());
        FieldNombre.setEnabled(!FieldNombre.isEnabled());
        FieldDireccion1.setEnabled(!FieldDireccion1.isEnabled());
        FieldDireccion2.setEnabled(!FieldDireccion2.isEnabled());
    }//GEN-LAST:event_RdoDomicilioMouseReleased

    private void BtnEscogerBaseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEscogerBaseMouseReleased
        FrameBases.setLocationRelativeTo(null);
        FrameBases.setSize(210, 235);
        FrameBases.setVisible(true);
    }//GEN-LAST:event_BtnEscogerBaseMouseReleased

    private void BtnEscogerIngreMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEscogerIngreMouseReleased
        FrameIngredientes.setLocationRelativeTo(null);
        FrameIngredientes.setSize(210, 304);
        FrameIngredientes.setVisible(true);
    }//GEN-LAST:event_BtnEscogerIngreMouseReleased

    private void RdoFinaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdoFinaMouseReleased
        LblListaBase.setText("Fina");
        LblPrecio.setText(CalcularMonto().toString());
        ChkBase.setSelected(true);
    }//GEN-LAST:event_RdoFinaMouseReleased

    private void RdoHiperfinaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdoHiperfinaMouseReleased
        LblListaBase.setText("Hiperfina");
        LblPrecio.setText(CalcularMonto().toString());
        ChkBase.setSelected(true);
    }//GEN-LAST:event_RdoHiperfinaMouseReleased

    private void RdoMegafaunaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdoMegafaunaMouseReleased
        LblListaBase.setText("Megafina");
        LblPrecio.setText(CalcularMonto().toString());
        ChkBase.setSelected(true);
    }//GEN-LAST:event_RdoMegafaunaMouseReleased

    private void RdoExtrafinaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdoExtrafinaMouseReleased
        LblListaBase.setText("Extrafina");
        LblPrecio.setText(CalcularMonto().toString());
        ChkBase.setSelected(true);
    }//GEN-LAST:event_RdoExtrafinaMouseReleased

    private void RdoMegaextrafinaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdoMegaextrafinaMouseReleased
        LblListaBase.setText("Megaextrafina");
        LblPrecio.setText(CalcularMonto().toString());
        ChkBase.setSelected(true);
    }//GEN-LAST:event_RdoMegaextrafinaMouseReleased

    private void RdoExtrahiperfinaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdoExtrahiperfinaMouseReleased
        LblListaBase.setText("Extrahiperfina");
        LblPrecio.setText(CalcularMonto().toString());
        ChkBase.setSelected(true);
    }//GEN-LAST:event_RdoExtrahiperfinaMouseReleased

    private void RdoHipermegafinaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdoHipermegafinaMouseReleased
        LblListaBase.setText("Hipermegafina");
        LblPrecio.setText(CalcularMonto().toString());
        ChkBase.setSelected(true);
    }//GEN-LAST:event_RdoHipermegafinaMouseReleased

    private void RdoHiperextramegafinaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdoHiperextramegafinaMouseReleased
        LblListaBase.setText("Hiperextramegafina");
        LblPrecio.setText(CalcularMonto().toString());
        ChkBase.setSelected(true);
    }//GEN-LAST:event_RdoHiperextramegafinaMouseReleased

    private void ChkChorizoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChkChorizoMouseReleased
        UpdateIngredientSummary();
        LblPrecio.setText(CalcularMonto().toString());
    }//GEN-LAST:event_ChkChorizoMouseReleased

    private void ChkJamonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChkJamonMouseReleased
        UpdateIngredientSummary();
        LblPrecio.setText(CalcularMonto().toString());
    }//GEN-LAST:event_ChkJamonMouseReleased

    private void ChkQuesoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChkQuesoMouseReleased
        UpdateIngredientSummary();
        LblPrecio.setText(CalcularMonto().toString());
    }//GEN-LAST:event_ChkQuesoMouseReleased

    private void ChkMorcillaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChkMorcillaMouseReleased
        UpdateIngredientSummary();
        LblPrecio.setText(CalcularMonto().toString());
    }//GEN-LAST:event_ChkMorcillaMouseReleased

    private void ChkChampiñonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChkChampiñonMouseReleased
        UpdateIngredientSummary();
        LblPrecio.setText(CalcularMonto().toString());
    }//GEN-LAST:event_ChkChampiñonMouseReleased

    private void ChkLubriganteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChkLubriganteMouseReleased
        UpdateIngredientSummary();
        LblPrecio.setText(CalcularMonto().toString());
    }//GEN-LAST:event_ChkLubriganteMouseReleased

    private void ChkGrelosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChkGrelosMouseReleased
        UpdateIngredientSummary();
        LblPrecio.setText(CalcularMonto().toString());
    }//GEN-LAST:event_ChkGrelosMouseReleased

    private void ChkPiñaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChkPiñaMouseReleased
        UpdateIngredientSummary();
        LblPrecio.setText(CalcularMonto().toString());
    }//GEN-LAST:event_ChkPiñaMouseReleased

    private void ChkMaracuyaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChkMaracuyaMouseReleased
        UpdateIngredientSummary();
        LblPrecio.setText(CalcularMonto().toString());
    }//GEN-LAST:event_ChkMaracuyaMouseReleased

    private void ChkChistorraMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChkChistorraMouseReleased
        UpdateIngredientSummary();
        LblPrecio.setText(CalcularMonto().toString());
    }//GEN-LAST:event_ChkChistorraMouseReleased

    private void ChkPolloMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChkPolloMouseReleased
        UpdateIngredientSummary();
        LblPrecio.setText(CalcularMonto().toString());
    }//GEN-LAST:event_ChkPolloMouseReleased

    private void BtnComprarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnComprarMouseReleased
        TicketDatosPizza = 
            "Base:\n" +
            LblListaBase.getText() + "\n\n" +
            "Ingredientes:\n" +
            LblListaIngre.getText()
                .replace("<html>", "")
                .replace("</html>", "")
                .replace("<br>", "\n")
            + "\n\n";
        TicketDatosDescue = 
            "Descuento:\n" +
            SelectedDescue() + "% - Codigo:" + FieldCodigo.getText() + "\n\n";
        TicketDatosDireccion = 
            "Direccion de domicilio:\n" +
            FieldNombre.getText() + "\n" +
            FieldDireccion1.getText() + "\n" +
            FieldDireccion2.getText() + "\n\n";
        TicketMonto =
            "Monto a pagar:\n" +
            CalcularMonto().toString();
        String TicketText = TicketDatosPizza; 
        
        if(FieldCodigo.isEnabled() && FieldCodigo.getText().isBlank()) {
            JOptionPane.showMessageDialog(null,
                    "Introduzca un código de descuento, o seleccione sin descuento",
                    "Opcion invalida",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if(FieldCodigo.isEnabled()) { TicketText += TicketDatosDescue; }
        if(RdoDomicilio.isSelected()) { TicketText += TicketDatosDireccion; }
        else { TicketText += "Pedido para recoger\n\n"; }
        TicketText += TicketMonto;
        AreaTicket.setText(TicketText);
        
        FrameTicket.setLocationRelativeTo(null);
        FrameTicket.setSize(291, 500);
        FrameTicket.setVisible(true);
    }//GEN-LAST:event_BtnComprarMouseReleased

    private void RdoCeroPorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdoCeroPorMouseReleased
        FieldCodigo.setEnabled(false);
        Descuento = 1.0f;
        LblPrecio.setText(CalcularMonto().toString());
    }//GEN-LAST:event_RdoCeroPorMouseReleased

    private void RdoDiezPorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdoDiezPorMouseReleased
        FieldCodigo.setEnabled(true);
        Descuento = 0.9f;
        LblPrecio.setText(CalcularMonto().toString());
    }//GEN-LAST:event_RdoDiezPorMouseReleased

    private void RdoVeintePorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdoVeintePorMouseReleased
        FieldCodigo.setEnabled(true);
        Descuento = 0.8f;
        LblPrecio.setText(CalcularMonto().toString());
    }//GEN-LAST:event_RdoVeintePorMouseReleased

    private void RdoVeinticincoPorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdoVeinticincoPorMouseReleased
        FieldCodigo.setEnabled(true);
        Descuento = 0.75f;
        LblPrecio.setText(CalcularMonto().toString());
    }//GEN-LAST:event_RdoVeinticincoPorMouseReleased

    private Float CalcularMonto() {
        Float Monto = 0.0f;
        
        for(var Rdo : RdoBases) {
            if(Rdo.isSelected()) { 
                Monto += PreciosBases.get(Rdo.getText());
                break;
            }
        }
        for(var Chk : ChkIngredientes) {
            if(Chk.isSelected()) { 
                Monto += PreciosIngre.get(Chk.getText());
            }
        }
        
        return (float)Math.floor( (Monto * Descuento) * 100) / 100;
    }
    
    private String SelectedDescue() {
        String Selected = "";
        
        for(var Rdo : RdoDescue) {
            if(Rdo.isSelected()) { 
                Selected = Rdo.getText();
                break;
            }
        }
        
        return Selected;
    }
    
    //TODO:
    //  Convertir el string generado a un formato generico y guardar a global
    //  Cambiar el texto del resumen de productos desde los controladores 
    //      Realizar el formateo de texto desde la llamada a setText()
    //      Actualizar el formateo en BtnComprarMouseReleased()
    private void UpdateIngredientSummary() {
        String IngreSummary = "";
        int SelectedCount = 0;
        
        for(var Ingre : ChkIngredientes) {
            if(Ingre.isSelected()) { 
                IngreSummary += Ingre.getText() + "<br>";
                SelectedCount++;
            }
        }
        
        if(SelectedCount > 0) { 
            ChkIngre.setSelected(true);
            IngreSummary = IngreSummary.substring(0, IngreSummary.length() - 4);
            IngreSummary = String.format("<html>%s</html>", IngreSummary);
        }
        else { 
            ChkIngre.setSelected(false);
            IngreSummary = DefaultIngreSummary;
        }
        
        LblListaIngre.setText(IngreSummary);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaTicket;
    private javax.swing.JButton BtnComprar;
    private javax.swing.JButton BtnEscogerBase;
    private javax.swing.JButton BtnEscogerIngre;
    private javax.swing.ButtonGroup BtngrpBases;
    private javax.swing.ButtonGroup BtngrpDescue;
    private javax.swing.JCheckBox ChkBase;
    private javax.swing.JCheckBox ChkChampiñon;
    private javax.swing.JCheckBox ChkChistorra;
    private javax.swing.JCheckBox ChkChorizo;
    private javax.swing.JCheckBox ChkGrelos;
    private javax.swing.JCheckBox ChkIngre;
    private javax.swing.JCheckBox ChkJamon;
    private javax.swing.JCheckBox ChkLubrigante;
    private javax.swing.JCheckBox ChkMaracuya;
    private javax.swing.JCheckBox ChkMorcilla;
    private javax.swing.JCheckBox ChkPiña;
    private javax.swing.JCheckBox ChkPollo;
    private javax.swing.JCheckBox ChkQueso;
    private javax.swing.JTextField FieldCodigo;
    private javax.swing.JTextField FieldDireccion1;
    private javax.swing.JTextField FieldDireccion2;
    private javax.swing.JTextField FieldNombre;
    private javax.swing.JFrame FrameBases;
    private javax.swing.JFrame FrameIngredientes;
    private javax.swing.JFrame FrameTicket;
    private javax.swing.JLabel LabelDescuentos;
    private javax.swing.JLabel LblBase;
    private javax.swing.JLabel LblBasesTitulo;
    private javax.swing.JLabel LblDireccion;
    private javax.swing.JLabel LblIngreTitulo;
    private javax.swing.JLabel LblIngredientes;
    private javax.swing.JLabel LblListaBase;
    private javax.swing.JLabel LblListaIngre;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblPrecio;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JPanel PanelBases;
    private javax.swing.JPanel PanelComprar;
    private javax.swing.JPanel PanelDatosDomicilio;
    private javax.swing.JPanel PanelDescuentos;
    private javax.swing.JPanel PanelIngredientes;
    private javax.swing.JPanel PanelPedido;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanelTicket;
    private javax.swing.JRadioButton RdoCeroPor;
    private javax.swing.JRadioButton RdoDiezPor;
    private javax.swing.JRadioButton RdoDomicilio;
    private javax.swing.JRadioButton RdoExtrafina;
    private javax.swing.JRadioButton RdoExtrahiperfina;
    private javax.swing.JRadioButton RdoFina;
    private javax.swing.JRadioButton RdoHiperextramegafina;
    private javax.swing.JRadioButton RdoHiperfina;
    private javax.swing.JRadioButton RdoHipermegafina;
    private javax.swing.JRadioButton RdoMegaextrafina;
    private javax.swing.JRadioButton RdoMegafauna;
    private javax.swing.JRadioButton RdoVeintePor;
    private javax.swing.JRadioButton RdoVeinticincoPor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
