/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.functionalguis;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Scheduler extends javax.swing.JFrame {

    DefaultTableModel TablaModel;
    File DataFile = new File("C:\\Users\\Usuario\\db.txt");
    enum Campos {
      NOMBRES,
      APELLIDOS,
      DNI,
      HORAE,
      HORAS,
    };
    Campos Dato;
    
    /**
     * Creates new form Scheduler
     * @throws java.io.IOException
     */
    public Scheduler() throws IOException {
        setLocationRelativeTo(null);
        initComponents();
        TablaModel = (DefaultTableModel)Tabla.getModel();

        FileReader DataFileReader = new FileReader(DataFile);
        BufferedReader DataFileBuffer = new BufferedReader(DataFileReader); 
        Vector<String> NewRowData;
        String ReadRowData;
        
        for(;(ReadRowData = DataFileBuffer.readLine()) != null;) {
            String[] CellData = ReadRowData.split(",");
            NewRowData = new Vector();
            for (String s : CellData) {
                NewRowData.add(s);
            }
            TablaModel.addRow(NewRowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameExplorador = new javax.swing.JFrame();
        PanelTabla = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        PanelExploradorCtl = new javax.swing.JPanel();
        BtnEliminarRegistro = new javax.swing.JButton();
        DialogResumen = new javax.swing.JDialog();
        PanelDR = new javax.swing.JPanel();
        LblDRNombres = new javax.swing.JLabel();
        LblDRApellidos = new javax.swing.JLabel();
        LblDRDNI = new javax.swing.JLabel();
        LblDRHoraE = new javax.swing.JLabel();
        LblDRHoraS = new javax.swing.JLabel();
        DialogDatosP = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        FieldNombres = new javax.swing.JTextField();
        FieldApellidos = new javax.swing.JTextField();
        FieldDNI = new javax.swing.JTextField();
        LblDDPNombres = new javax.swing.JLabel();
        LblDDPApellidos = new javax.swing.JLabel();
        LblDDPDNI = new javax.swing.JLabel();
        DialogHoraE = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        LblDHEHoraE = new javax.swing.JLabel();
        FieldHoraE = new javax.swing.JTextField();
        DialogHoraS = new javax.swing.JDialog();
        LblDHSHoraS = new javax.swing.JLabel();
        FieldHoraS = new javax.swing.JTextField();
        PanelEditar = new javax.swing.JPanel();
        BtnDatosP = new javax.swing.JButton();
        BtnHoraE = new javax.swing.JButton();
        BtnHoraS = new javax.swing.JButton();
        LblTituloPanelEditar = new javax.swing.JLabel();
        PanelMeta = new javax.swing.JPanel();
        BtnVerResum = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        BtnVerTodos = new javax.swing.JButton();
        SeparadorPrincipal = new javax.swing.JSeparator();

        FrameExplorador.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        FrameExplorador.setType(java.awt.Window.Type.UTILITY);

        Tabla.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombres", "Apellidos", "DNI", "H. Entrada", "H. Salida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PanelTabla.setViewportView(Tabla);

        BtnEliminarRegistro.setText("Eliminar");
        BtnEliminarRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnEliminarRegistroMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout PanelExploradorCtlLayout = new javax.swing.GroupLayout(PanelExploradorCtl);
        PanelExploradorCtl.setLayout(PanelExploradorCtlLayout);
        PanelExploradorCtlLayout.setHorizontalGroup(
            PanelExploradorCtlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelExploradorCtlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnEliminarRegistro)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        PanelExploradorCtlLayout.setVerticalGroup(
            PanelExploradorCtlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelExploradorCtlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnEliminarRegistro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FrameExploradorLayout = new javax.swing.GroupLayout(FrameExplorador.getContentPane());
        FrameExplorador.getContentPane().setLayout(FrameExploradorLayout);
        FrameExploradorLayout.setHorizontalGroup(
            FrameExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameExploradorLayout.createSequentialGroup()
                .addComponent(PanelExploradorCtl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        FrameExploradorLayout.setVerticalGroup(
            FrameExploradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameExploradorLayout.createSequentialGroup()
                .addComponent(PanelExploradorCtl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(PanelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        DialogResumen.setTitle("Resumen");
        DialogResumen.setResizable(false);
        DialogResumen.setType(java.awt.Window.Type.UTILITY);

        LblDRNombres.setText("Nombres: " + FieldNombres.getText());

        LblDRApellidos.setText("Apellidos: " + FieldApellidos.getText());

        LblDRDNI.setText("DNI: " + FieldDNI.getText());

        LblDRHoraE.setText("Hora de entrada: " + FieldHoraE.getText());

        LblDRHoraS.setText("Hora de salida: " + FieldHoraS.getText());

        javax.swing.GroupLayout PanelDRLayout = new javax.swing.GroupLayout(PanelDR);
        PanelDR.setLayout(PanelDRLayout);
        PanelDRLayout.setHorizontalGroup(
            PanelDRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDRLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblDRNombres)
                    .addComponent(LblDRApellidos)
                    .addComponent(LblDRDNI)
                    .addComponent(LblDRHoraE)
                    .addComponent(LblDRHoraS))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        PanelDRLayout.setVerticalGroup(
            PanelDRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDRLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblDRNombres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblDRApellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblDRDNI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblDRHoraE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblDRHoraS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DialogResumenLayout = new javax.swing.GroupLayout(DialogResumen.getContentPane());
        DialogResumen.getContentPane().setLayout(DialogResumenLayout);
        DialogResumenLayout.setHorizontalGroup(
            DialogResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogResumenLayout.setVerticalGroup(
            DialogResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        DialogDatosP.setTitle("Datos personales");
        DialogDatosP.setResizable(false);
        DialogDatosP.setType(java.awt.Window.Type.UTILITY);

        FieldNombres.setText(".");
        FieldNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FieldNombresKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FieldNombresKeyTyped(evt);
            }
        });

        FieldApellidos.setText(".");
        FieldApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FieldApellidosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FieldApellidosKeyTyped(evt);
            }
        });

        FieldDNI.setText(".");
        FieldDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FieldDNIKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FieldDNIKeyTyped(evt);
            }
        });

        LblDDPNombres.setText("Nombres");

        LblDDPApellidos.setText("Apellidos");

        LblDDPDNI.setText("DNI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblDDPNombres)
                            .addComponent(LblDDPApellidos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(FieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(FieldNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LblDDPDNI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDDPNombres)
                    .addComponent(FieldNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDDPApellidos)
                    .addComponent(FieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDDPDNI)
                    .addComponent(FieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DialogDatosPLayout = new javax.swing.GroupLayout(DialogDatosP.getContentPane());
        DialogDatosP.getContentPane().setLayout(DialogDatosPLayout);
        DialogDatosPLayout.setHorizontalGroup(
            DialogDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        DialogDatosPLayout.setVerticalGroup(
            DialogDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        DialogHoraE.setTitle("Datos personales");
        DialogHoraE.setResizable(false);
        DialogHoraE.setType(java.awt.Window.Type.UTILITY);

        LblDHEHoraE.setText("Hora de Entrada");

        FieldHoraE.setText(".");
        FieldHoraE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FieldHoraEKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FieldHoraEKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblDHEHoraE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FieldHoraE, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDHEHoraE)
                    .addComponent(FieldHoraE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DialogHoraELayout = new javax.swing.GroupLayout(DialogHoraE.getContentPane());
        DialogHoraE.getContentPane().setLayout(DialogHoraELayout);
        DialogHoraELayout.setHorizontalGroup(
            DialogHoraELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        DialogHoraELayout.setVerticalGroup(
            DialogHoraELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        DialogHoraS.setTitle("Datos personales");
        DialogHoraS.setResizable(false);
        DialogHoraS.setType(java.awt.Window.Type.UTILITY);

        LblDHSHoraS.setText("Hora de Salida");

        FieldHoraS.setText(".");
        FieldHoraS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FieldHoraSKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FieldHoraSKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout DialogHoraSLayout = new javax.swing.GroupLayout(DialogHoraS.getContentPane());
        DialogHoraS.getContentPane().setLayout(DialogHoraSLayout);
        DialogHoraSLayout.setHorizontalGroup(
            DialogHoraSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogHoraSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblDHSHoraS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FieldHoraS, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DialogHoraSLayout.setVerticalGroup(
            DialogHoraSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogHoraSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialogHoraSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDHSHoraS)
                    .addComponent(FieldHoraS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scheduler");
        setResizable(false);

        BtnDatosP.setText("...Datos personales");
        BtnDatosP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BtnDatosP.setMargin(new java.awt.Insets(2, 4, 2, 4));
        BtnDatosP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnDatosPMouseReleased(evt);
            }
        });

        BtnHoraE.setText("...Hora de Entrada");
        BtnHoraE.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BtnHoraE.setMargin(new java.awt.Insets(2, 4, 2, 4));
        BtnHoraE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnHoraEMouseReleased(evt);
            }
        });

        BtnHoraS.setText("...Hora de Salida");
        BtnHoraS.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BtnHoraS.setMargin(new java.awt.Insets(2, 4, 2, 4));
        BtnHoraS.setMaximumSize(new java.awt.Dimension(93, 22));
        BtnHoraS.setMinimumSize(new java.awt.Dimension(93, 22));
        BtnHoraS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnHoraSMouseReleased(evt);
            }
        });

        LblTituloPanelEditar.setText("Editar...");

        javax.swing.GroupLayout PanelEditarLayout = new javax.swing.GroupLayout(PanelEditar);
        PanelEditar.setLayout(PanelEditarLayout);
        PanelEditarLayout.setHorizontalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnHoraE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelEditarLayout.createSequentialGroup()
                        .addComponent(LblTituloPanelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(BtnDatosP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnHoraS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelEditarLayout.setVerticalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTituloPanelEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnDatosP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnHoraE, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnHoraS, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtnVerResum.setText("Ver resumen");
        BtnVerResum.setMargin(new java.awt.Insets(2, 4, 2, 4));
        BtnVerResum.setPreferredSize(new java.awt.Dimension(49, 22));
        BtnVerResum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnVerResumMouseReleased(evt);
            }
        });

        BtnGuardar.setText("Guardar");
        BtnGuardar.setMargin(new java.awt.Insets(2, 4, 2, 4));
        BtnGuardar.setMaximumSize(new java.awt.Dimension(71, 22));
        BtnGuardar.setMinimumSize(new java.awt.Dimension(71, 22));
        BtnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnGuardarMouseReleased(evt);
            }
        });

        BtnVerTodos.setText("Ver todos");
        BtnVerTodos.setMargin(new java.awt.Insets(2, 4, 2, 4));
        BtnVerTodos.setPreferredSize(new java.awt.Dimension(49, 22));
        BtnVerTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnVerTodosMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout PanelMetaLayout = new javax.swing.GroupLayout(PanelMeta);
        PanelMeta.setLayout(PanelMetaLayout);
        PanelMetaLayout.setHorizontalGroup(
            PanelMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMetaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(BtnVerResum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnVerTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelMetaLayout.setVerticalGroup(
            PanelMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMetaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnVerResum, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnVerTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SeparadorPrincipal.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeparadorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelMeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SeparadorPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PanelMeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDatosPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDatosPMouseReleased
        DialogDatosP.setLocationRelativeTo(null);
        DialogDatosP.setSize(206,117);
        DialogDatosP.setVisible(true);
    }//GEN-LAST:event_BtnDatosPMouseReleased

    private void BtnHoraEMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHoraEMouseReleased
        DialogHoraE.setLocationRelativeTo(null);
        DialogHoraE.setSize(249,65);
        DialogHoraE.setVisible(true);
    }//GEN-LAST:event_BtnHoraEMouseReleased

    private void BtnHoraSMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHoraSMouseReleased
        DialogHoraS.setLocationRelativeTo(null);
        DialogHoraS.setSize(239,65);
        DialogHoraS.setVisible(true);
    }//GEN-LAST:event_BtnHoraSMouseReleased

    private void BtnVerResumMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVerResumMouseReleased
        ActualizarResumen();
        DialogResumen.setLocationRelativeTo(null);
        DialogResumen.setSize(245, 140);
        DialogResumen.setVisible(true);
    }//GEN-LAST:event_BtnVerResumMouseReleased

    private void BtnVerTodosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVerTodosMouseReleased
        FrameExplorador.setLocationRelativeTo(null);
        FrameExplorador.setSize(500, 255);
        FrameExplorador.setVisible(true);
    }//GEN-LAST:event_BtnVerTodosMouseReleased

    private void BtnGuardarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGuardarMouseReleased
        //Agrega los valores introducidos a la tabla como nueva fila
        Object[] RowData = new Object[]{
            FieldNombres.getText(),
            FieldApellidos.getText(),
            FieldDNI.getText(),
            FieldHoraE.getText(),
            FieldHoraS.getText(),
        };
        TablaModel.addRow(RowData);
        
        //Guarda la nueva fila en el archivo
        try(FileWriter OutWriter = new FileWriter(DataFile, true)) {
            
            int ColsInTabla = TablaModel.getColumnCount(), RowsInTabla = TablaModel.getRowCount();
            String RowToSave = "";
            
            for(int i = 0; i < ColsInTabla; i++) { 
                RowToSave += TablaModel.getDataVector().elementAt(RowsInTabla - 1).elementAt(i).toString() + ',';
            }
            OutWriter.write(RowToSave + '\n');
            OutWriter.close();
        } catch (IOException ex) {
            Logger.getLogger(FileCopy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnGuardarMouseReleased

    private void BtnEliminarRegistroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarRegistroMouseReleased
        int[] SelectedRows = Tabla.getSelectedRows();
        
        for(int Row : SelectedRows){ TablaModel.removeRow(Row); }
        
        //Rewrites the entire goddamned database file
        try(FileWriter OutWriter = new FileWriter(DataFile)) {
            int ColsInTabla = TablaModel.getColumnCount(), 
                RowsInTabla = TablaModel.getRowCount();
            String RowsToSave = "";
            
            for(int i = 0; i < RowsInTabla; i++) {
                for(int j = 0; j < ColsInTabla; j++) {
                    RowsToSave += TablaModel.getDataVector().elementAt(i).elementAt(j).toString() + ',';
                }
                RowsToSave += '\n';
            }
            OutWriter.write(RowsToSave);
            OutWriter.close();
        } catch (IOException ex) {
            Logger.getLogger(FileCopy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnEliminarRegistroMouseReleased

    private void FieldNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldNombresKeyTyped
        
    }//GEN-LAST:event_FieldNombresKeyTyped

    private void FieldApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldApellidosKeyTyped
        
    }//GEN-LAST:event_FieldApellidosKeyTyped

    private void FieldDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldDNIKeyTyped
        
    }//GEN-LAST:event_FieldDNIKeyTyped

    private void FieldHoraEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldHoraEKeyTyped
        
    }//GEN-LAST:event_FieldHoraEKeyTyped

    private void FieldHoraSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldHoraSKeyTyped
        
    }//GEN-LAST:event_FieldHoraSKeyTyped

    private void FieldNombresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldNombresKeyReleased
        ActualizarResumen(Campos.NOMBRES);
    }//GEN-LAST:event_FieldNombresKeyReleased

    private void FieldApellidosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldApellidosKeyReleased
        ActualizarResumen(Campos.APELLIDOS);
    }//GEN-LAST:event_FieldApellidosKeyReleased

    private void FieldDNIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldDNIKeyReleased
        ActualizarResumen(Campos.DNI);
    }//GEN-LAST:event_FieldDNIKeyReleased

    private void FieldHoraEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldHoraEKeyReleased
        ActualizarResumen(Campos.HORAE);
    }//GEN-LAST:event_FieldHoraEKeyReleased

    private void FieldHoraSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldHoraSKeyReleased
        ActualizarResumen(Campos.HORAS);
    }//GEN-LAST:event_FieldHoraSKeyReleased

    private void ActualizarResumen(Campos CualesDatos) {
        switch(CualesDatos) {
        case NOMBRES -> { LblDRNombres.setText("Nombres: " + FieldNombres.getText()); }
        case APELLIDOS -> { LblDRApellidos.setText("Apellidos: " + FieldApellidos.getText()); }
        case DNI -> { LblDRDNI.setText("DNI: " + FieldDNI.getText()); }
        case HORAE -> { LblDRHoraE.setText("Hora de entrada: " + FieldHoraE.getText()); }
        case HORAS -> { LblDRHoraS.setText("Hora de salida: " + FieldHoraS.getText()); }
        }
    }
    
    private void ActualizarResumen() {
        LblDRNombres.setText("Nombres: " + FieldNombres.getText());
        LblDRApellidos.setText("Apellidos: " + FieldApellidos.getText());
        LblDRDNI.setText("DNI: " + FieldDNI.getText());
        LblDRHoraE.setText("Hora de entrada: " + FieldHoraE.getText());
        LblDRHoraS.setText("Hora de salida: " + FieldHoraS.getText());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Scheduler().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Scheduler.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDatosP;
    private javax.swing.JButton BtnEliminarRegistro;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnHoraE;
    private javax.swing.JButton BtnHoraS;
    private javax.swing.JButton BtnVerResum;
    private javax.swing.JButton BtnVerTodos;
    private javax.swing.JDialog DialogDatosP;
    private javax.swing.JDialog DialogHoraE;
    private javax.swing.JDialog DialogHoraS;
    private javax.swing.JDialog DialogResumen;
    private javax.swing.JTextField FieldApellidos;
    private javax.swing.JTextField FieldDNI;
    private javax.swing.JTextField FieldHoraE;
    private javax.swing.JTextField FieldHoraS;
    private javax.swing.JTextField FieldNombres;
    private javax.swing.JFrame FrameExplorador;
    private javax.swing.JLabel LblDDPApellidos;
    private javax.swing.JLabel LblDDPDNI;
    private javax.swing.JLabel LblDDPNombres;
    private javax.swing.JLabel LblDHEHoraE;
    private javax.swing.JLabel LblDHSHoraS;
    private javax.swing.JLabel LblDRApellidos;
    private javax.swing.JLabel LblDRDNI;
    private javax.swing.JLabel LblDRHoraE;
    private javax.swing.JLabel LblDRHoraS;
    private javax.swing.JLabel LblDRNombres;
    private javax.swing.JLabel LblTituloPanelEditar;
    private javax.swing.JPanel PanelDR;
    private javax.swing.JPanel PanelEditar;
    private javax.swing.JPanel PanelExploradorCtl;
    private javax.swing.JPanel PanelMeta;
    private javax.swing.JScrollPane PanelTabla;
    private javax.swing.JSeparator SeparadorPrincipal;
    private javax.swing.JTable Tabla;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
