/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.frame2;

/**
 *
 * @author Usuario
 */
public class Macros extends javax.swing.JFrame {

    /**
     * Creates new form frame2
     */
    public Macros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MacrosOO = new javax.swing.JPanel();
        NomMacro = new javax.swing.JLabel();
        Macrode = new javax.swing.JLabel();
        Macroexis = new javax.swing.JLabel();
        MacroNom = new javax.swing.JTextField();
        Macro = new javax.swing.JScrollPane();
        Macrodesde = new javax.swing.JTextArea();
        ExistenMacro = new javax.swing.JScrollPane();
        Eximac = new javax.swing.JTextArea();
        BEjecutar = new javax.swing.JButton();
        BCerrar = new javax.swing.JButton();
        BAsignar = new javax.swing.JButton();
        BEditar = new javax.swing.JButton();
        BNuevo = new javax.swing.JButton();
        BAdministrar = new javax.swing.JButton();
        BAyuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Macros básicas de Open Office.org");

        MacrosOO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        MacrosOO.setName("Macros"); // NOI18N

        NomMacro.setText("Nombre de la macro");
        NomMacro.setName("NombreM"); // NOI18N

        Macrode.setText("Macro desde");
        Macrode.setName(""); // NOI18N

        Macroexis.setText("Macros existentes en:");

        MacroNom.setName("Macrst"); // NOI18N

        Macrodesde.setColumns(20);
        Macrodesde.setRows(5);
        Macrodesde.setName(""); // NOI18N
        Macro.setViewportView(Macrodesde);

        Eximac.setColumns(20);
        Eximac.setRows(5);
        ExistenMacro.setViewportView(Eximac);

        BEjecutar.setText("Ejecutar");
        BEjecutar.setEnabled(false);

        BCerrar.setText("Cerrar");
        BCerrar.setName("BotonCerrar"); // NOI18N

        BAsignar.setText("Asignar");
        BAsignar.setEnabled(false);
        BAsignar.setName("BotonAsignar"); // NOI18N

        BEditar.setText("Editar");
        BEditar.setEnabled(false);
        BEditar.setName("BotonEditar"); // NOI18N

        BNuevo.setText("Nuevo");
        BNuevo.setName("BotonNuevo"); // NOI18N

        BAdministrar.setText("Administrar");
        BAdministrar.setName("Botonadm"); // NOI18N

        BAyuda.setText("Ayuda");
        BAyuda.setName("Botonayuda"); // NOI18N

        javax.swing.GroupLayout MacrosOOLayout = new javax.swing.GroupLayout(MacrosOO);
        MacrosOO.setLayout(MacrosOOLayout);
        MacrosOOLayout.setHorizontalGroup(
            MacrosOOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MacrosOOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MacrosOOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomMacro)
                    .addGroup(MacrosOOLayout.createSequentialGroup()
                        .addComponent(Macro, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(ExistenMacro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(MacroNom, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MacrosOOLayout.createSequentialGroup()
                        .addComponent(Macrode)
                        .addGap(202, 202, 202)
                        .addComponent(Macroexis)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(MacrosOOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BAyuda)
                    .addComponent(BEjecutar)
                    .addComponent(BCerrar)
                    .addComponent(BAsignar)
                    .addComponent(BEditar)
                    .addComponent(BNuevo)
                    .addComponent(BAdministrar))
                .addGap(25, 25, 25))
        );
        MacrosOOLayout.setVerticalGroup(
            MacrosOOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MacrosOOLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(MacrosOOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NomMacro)
                    .addComponent(BEjecutar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MacrosOOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MacroNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCerrar))
                .addGroup(MacrosOOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MacrosOOLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(MacrosOOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Macrode)
                            .addComponent(Macroexis))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MacrosOOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Macro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ExistenMacro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MacrosOOLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(BAsignar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BAdministrar)))
                .addGap(18, 18, 18)
                .addComponent(BAyuda)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        Macrode.getAccessibleContext().setAccessibleName("Macro");
        BEjecutar.getAccessibleContext().setAccessibleName("BotonEjecutar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MacrosOO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(MacrosOO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        MacrosOO.getAccessibleContext().setAccessibleName("Macros");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Macros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Macros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Macros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Macros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Macros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAdministrar;
    private javax.swing.JButton BAsignar;
    private javax.swing.JButton BAyuda;
    private javax.swing.JButton BCerrar;
    private javax.swing.JButton BEditar;
    private javax.swing.JButton BEjecutar;
    private javax.swing.JButton BNuevo;
    private javax.swing.JTextArea Eximac;
    private javax.swing.JScrollPane ExistenMacro;
    private javax.swing.JScrollPane Macro;
    private javax.swing.JTextField MacroNom;
    private javax.swing.JLabel Macrode;
    private javax.swing.JTextArea Macrodesde;
    private javax.swing.JLabel Macroexis;
    private javax.swing.JPanel MacrosOO;
    private javax.swing.JLabel NomMacro;
    // End of variables declaration//GEN-END:variables
}
