all: Thread1 Thread2 Thread3 Thread4 Thread5 ThreadApuntes Thread21 Thread22
Thread1: Thread1.c
	gcc Thread1.c -o Thread1.out
Thread2: Thread2.c
	gcc Thread2.c -o Thread2.out
Thread3: Thread3.c
	gcc Thread3.c -o Thread3.out
Thread4: Thread4.c
	gcc Thread4.c -o Thread4.out
Thread5: Thread5.c
	gcc Thread5.c -o Thread5.out
ThreadApuntes: ThreadApuntes.c
	gcc ThreadApuntes.c -o ThreadApuntes.out
Thread21: Thread21.c
	gcc Thread21.c -o Thread21.out
Thread: Thread22.c
	gcc Thread22.c -o Thread22.out
clean:
	rm *.out

