all: ef ef2 ef3 fp fp2 fp3
 
ef: ejercicio1-7.c
	gcc ejercicio1-7.c -o ejercicio1-7.out

ef2: ejercicio1-8.c
	gcc ejercicio1-8.c -o ejercicio1-8.out

ef3: ejercicio3-2.c
	gcc ejercicio3-2.c -o ejercicio3-2.out

fp: forkprog.c
	gcc forkprog.c -o forkprog.out

fp2: forkprog2.c
	gcc forkprog2.c -o forkprog2.out

fp3: forkprog3.c
	gcc forkprog3.c -o forkprog3.out

clean:
	rm ejercicio*.out
	rm forkprog*.out
