
obj-m := nothing.o

main: calcu+.c 
	gcc calcu+.c -o calcu+.out
	gcc Creararchivo.c -o Creararchivo.out
	gcc forprog1.c -o forprog1.out
	gcc Hilos1.c -o Hilos1.out -lpthread
	gcc Hilos2.c -o Hilos2.out -lpthread
	gcc Hilos3.c -o Hilos3.out -lpthread
	gcc Hilos4.c -o Hilos4.out -lpthread
	gcc Hilos5.c -o Hilos5.out -lpthread
	gcc procesos2.c -o procesos2.out
	gcc procesos.c -o procesos.out
	gcc prog1.c -o prog1.out
	gcc prog2.c -o prog2.out
	gcc prog3.c -o prog3.out
	gcc prog4.c -o prog4.out
	gcc thread11.c -o thread11.out -lpthread
	

clean:
	rm calcu+.out
	rm Creararchivo.out
	rm forprog1.out
	rm Hilos1.out
	rm Hilos2.out
	rm Hilos3.out
	rm Hilos4.out
	rm Hilos5.out
	rm procesos2.out
	rm procesos.out
	rm prog1.out
	rm prog2.out
	rm prog3.out
	rm prog4.out
	rm thread11.out
	
	


