all: 1_formas.cpp lib/forma.h lib/rectangulo.h lib/elipse.h lib/circulo.h lib/cuadrado.h 2_empresa.cpp lib/empleado.h lib/secretario.h lib/vendedor.h lib/jefezona.h
	g++ 1_formas.cpp -o formas.o
	g++ 2_empresa.cpp -o empresa.o
clear:
	rm -f *.o
