build: build_1 build_2 build_3 build_4 build_5 build_7 build_8 build_9 build_10
build_1:
	make build -C 1
build_2:
	make build -C 2
build_3:
	make build -C 3
build_4:
	make build -C 4
build_5:
	make build -C 5
build_7:
	make build -C 7
build_8:
	make build -C 8
build_9:
	make build -C 9
build_10:
	make build -C 10
clean: clean_1 clean_2 clean_3 clean_4 clean_5 clean_7 clean_8 clean_9 clean_10
clean_1: 
	make clean -C 1 -i
clean_2:
	make clean -C 2 -i
clean_3:
	make clean -C 3 -i
clean_4:
	make clean -C 4 -i
clean_5:
	make clean -C 5 -i
clean_7:
	make clean -C 7 -i
clean_8:
	make clean -C 8 -i
clean_9:
	make clean -C 9 -i
clean_10:
	make clean -C 10 -i
